### ISSUE TITLE
介绍里面的 图标 怎么弄

### ISSUE THREAD

**Issue by dfgf123** [MemeMayhem/ModExamples#101]

**Comment by fx013** [comment]
文字里使用的游戏内置图标一般用`GameMechanicTags.TAG.XXX`，教程里有用到，所有能用的TAG在这里可查：https://github.com/MemeMayhem/ModExamples/blob/main/References/GameMechanicTags.lua.txt

如果是要加自定义的图标，可以参考这个有自定义图标的例子：
https://github.com/MemeMayhem/ModExamples/tree/main/Medium-PoisonTimer

这个例子里角色的名字就是有自定义图标的，这些图标可以用在任意文字描述里。
