### ISSUE TITLE
The ultimate may cause multiple damages 终极技能会造成多段伤害

### ISSUE THREAD

**Issue by Penguin134** [MemeMayhem/ModExamples#102]
This bug occurs when `Api:SetUltimateLaunchSound()` is called without using the `Api:SetUltimateHitSound()`. 
当调用`Api:SetUltimateLaunchSound()`而没有调用`Api:SetUltimateHitSound()`时，就会出现这个bug。

https://github.com/user-attachments/assets/d69dab10-a3a6-4c15-a05d-ed2472cf5ff9

**Comment by GoodCrispyShark** [comment]
这个看起来是lua报错了 建议查一下log看一下error
