### ISSUE TITLE
Relic "Pig Book" reference

### ISSUE THREAD

**Issue by AirHater** [MemeMayhem/ModExamples#103]
![image](https://github.com/user-attachments/assets/1c5cc7a9-a9bf-4ebb-ab71-1f89186a0351)
![image](https://github.com/user-attachments/assets/75d251da-5eac-462f-ab2d-61a7435dbe3f)
I tried using Api.GameMechanicTags.RELIC_ICON.pig_book to get the icon of this combo relic, but i got an exception. Its listed as "big_book" in both https://github.com/MemeMayhem/ModExamples/blob/aaaa8e1cebfdd675b3521cd400b44b7415c1148f/References/RelicData.lua.txt and via Api:PrintRelics(), but it doesnt have an actual icon reference?
Also, is there a way to remove relics during the event, similar to combat_unit:RemoveRelic(name) in the outside?

**Comment by GoodCrispyShark** [comment]
not all relics have RELIC_ICON
only the ones that can be combined have this

**Comment by AirHater** [comment]
Champion Trophy (id = "blue_ribbon") doesnt seem to have RELIC_ICON either. and its not a combo relic, but just a legendary

**Comment by GoodCrispyShark** [comment]
i dont quite get what removing relic in outside mean? do you mean you want to block it in relic pool?

**Comment by AirHater** [comment]
i wanted to ask if its possible to remove relic in the event/choice, similar to how its possible to do in the combat via combat_unit:RemoveRelic(name)

**Comment by GoodCrispyShark** [comment]
You should be able to do so by calling the same function
Did they persist in the next wave?

**Comment by AirHater** [comment]
i dont really understand where am i supposed to add that function. am i supposed to call it something like
`Api:RegisterChoice(event, function(combat_unit)
local relic = "blue_fish"
combat_unit:RemoveRelic(name)
end)`
but than it would remove it relic regardless of what you chose in the event (if that code even works). how am i supposed to add a function to a specific choice event?

**Comment by fx013** [comment]
@AirHater The `Api:RegisterChoice` API doesn't support callback functions. Is there any existing choice event in the game that removes relics? If not, this functionality likely is not there. Instead of removing relics, maybe add a relic that negates the effect of the relic you want to remove?

**Comment by GoodCrispyShark** [comment]
Combo relic would remove the required relics. 
Hope this is useful for now

**Comment by AirHater** [comment]
unfortunately that wasnt much useful. i guess i will try adding hidden attribute, and than have onBeforeCombatStart check to remove the relic, for now

**Comment by AirHater** [comment]
the way to remove relics in the events was added, so i see no reason to have that issue open
