### ISSUE TITLE
blocked_tooltips 无法生效（？）

### ISSUE THREAD

**Issue by fuxiao1563** [MemeMayhem/ModExamples#104]
![QQ20241007-181555](https://github.com/user-attachments/assets/46701dbb-5ace-4e71-b0ad-fd945fbaf78b)
`extra_tooltips = {{name = "health_per_second",type = "attribute", },},	
blocked_tooltips = { health_percentage_per_second = attribute, },
modify_attributes = {health_percentage_per_second = 0.01,},`

如图，因为修改 `health_percentage_per_second` 所以触发了tips
但使用 `blocked_tooltips` 关闭不了（我看硬汉用这个好像就能关上）

**Comment by Ill-cat** [comment]
加双引号
```
health_percentage_per_second = "attribute",
```

**Comment by fuxiao1563** [comment]
铸币了（）
