### ISSUE TITLE
开局对自己造成伤害怎么搞的来着

### ISSUE THREAD

**Issue by iddsxbk** [MemeMayhem/ModExamples#106]
用这个方法combat_unit:RegisterOnCombatStartCallback(name, function (level, target)的话，没有传入caster,那caster:damage()是没法用了吗

**Comment by fx013** [comment]
`RegisterOnCombatStartCallback`~~回调里的`target`就是玩家角色，用`target:Damage()`就可以了~~。或者也可以用`combat_unit:Damage()`

**Comment by iddsxbk** [comment]
还得是combat_unit。target：damage还是对敌人造成伤害，里面的参数target就是自己了
