### ISSUE TITLE
怎么设置子弹的伤害增加

### ISSUE THREAD

**Issue by iddsxbk** [MemeMayhem/ModExamples#107]
比如硬化石头，斧子100%这种卡的能力，感觉之前看到过类似的问题。但是没记下来

**Comment by fx013** [comment]
在子弹的伤害函数里你可以根据角色当前有哪些能力或者神器来计算伤害值。比如这里有个根据当前生命计算伤害的例子：https://github.com/MemeMayhem/ModExamples/issues/93#issue-2566263162

另外你也可以在能力上注册`RegisterOnMissileImpactCallback`回调，然后在回调里调整子弹伤害，这种方法可以让能力影响任意子弹伤害：https://github.com/MemeMayhem/ModExamples/issues/38#issuecomment-2364270162

**Comment by iddsxbk** [comment]
好的
