### ISSUE TITLE
能不能拿到boss的id这类信息

### ISSUE THREAD

**Issue by iddsxbk** [MemeMayhem/ModExamples#109]
比如CombatUnit:IsBoss()，CombatUnit:IsFinalBoss()这俩应该是确认boss的，那能知道是哪个boss吗，有没有类似getid()这种方法。这俩都没在案例里找到调用的。
还有CombatUnit:IsHero()和CombatUnit:IsMob()，是确认玩家和道中小怪的吧

**Comment by GoodCrispyShark** [comment]
可以用CombatUnit.mod_id
是的
