### ISSUE TITLE
Mods with conflicting character ids

### ISSUE THREAD

**Issue by fx013** [MemeMayhem/ModExamples#11]
When multiple mods use the same character id (e.g. use the same tutorial character id with different textures), the characters will be mixed up.

The following 2 mods are conflicting:
https://steamcommunity.com/sharedfiles/filedetails/?id=3329331596
https://steamcommunity.com/sharedfiles/filedetails/?id=3332871238

**Comment by MajorMajorMajor6** [comment]
temp fix in 0.20.130
![image](https://github.com/user-attachments/assets/8afa996f-66e8-425a-bd3d-78356d304e04)

**Comment by mbomb007** [comment]
Perhaps mods should prefix anything they add with a "mod ID" or something? Similar to how namespaces work in programming languages?

**Comment by fx013** [comment]
Yeah, we can use a naming convention like that in our wiki/examples to help reduce such conflicts. There will still be conflicts though so some error messages should still help.
