### ISSUE TITLE
怎么获取敌人BUFF状态层数

### ISSUE THREAD

**Issue by System2c** [MemeMayhem/ModExamples#110]
如图红框所示，我想获取敌人相关buff的层数，请问有什么api吗？
我尝试使用target:GetRelicLevel(name)，返回的应该是抗压神器数而不是buff层数。

![image](https://github.com/user-attachments/assets/7f15571c-bb1d-48fa-8b28-767d4514df57)

**Comment by GoodCrispyShark** [comment]
今天更新后可以使用
taget:GetBehaviorStackCount(behavior_name)来获得

**Comment by System2c** [comment]
> 今天更新后可以使用 taget:GetBehaviorStackCount(behavior_name)来获得

感谢！
