### ISSUE TITLE
关于子弹动画的问题

### ISSUE THREAD

**Issue by FasciA647** [MemeMayhem/ModExamples#117]
今天下午刚更新后，一些子弹会在飞出一小段距离后消失。具体见下
另外有一些关于制作子弹动画的问题：
1.能够改变子弹的飞行时间吗？改了flight_time后动画还是原来的速度。
2.怎样根据子弹发射方向改变旋转方向？

**Comment by FasciA647** [comment]
![子弹消失](https://github.com/user-attachments/assets/1fee1f46-b79a-4704-a34f-6d8ec559fe33)
只是显示上消失，也会命中。似乎与旋转速度有关，大于一定数值时会出现。

**Comment by GoodCrispyShark** [comment]
子弹目前写死0.75s后会消失
如果要更长更短都需要更多API支持

**Comment by FasciA647** [comment]
好的，因为想制作一些与子弹飞行速度有关的能力，希望能够添加。
另外怎么获取子弹发射方向的信息呢？

**Comment by GoodCrispyShark** [comment]
attack_data里应该有
attack_data.direct_move 是否直线移动
attack_data.direction 0是左，1是右
注意敌我是反过来的

**Comment by FasciA647** [comment]
感谢解答。
