### ISSUE TITLE
[BUG] 炸得能力卡“碳盾”伤害修正显示问题

### ISSUE THREAD

**Issue by System2c** [MemeMayhem/ModExamples#118]
由于steam上想发讨论话题被提示说发得太频繁（其实只发过两条），所以来这里提交bug

如题所属，炸得在启动时获得20血糖，进入高血糖状态，此时按照“碳盾”，应该获得-30%伤害修正，总体应为-40%，但是显示的却只有开局启动“玉玉”的-10%。

![bug1](https://github.com/user-attachments/assets/3c4c37c2-accb-4ba0-bb07-607d057ccbcd)
![bug2](https://github.com/user-attachments/assets/b375473c-c581-43b9-9837-5894b42f0f3d)

**Comment by GoodCrispyShark** [comment]
碳盾目前只会在战前检测一次血糖，今天的更新我添加了一个描述来减少歧义
