### ISSUE TITLE
wiki中部分BOSS的id似乎不正确

### ISSUE THREAD

**Issue by FasciA647** [MemeMayhem/ModExamples#119]
![疑似bossid错误](https://github.com/user-attachments/assets/36a1af7d-7c76-405c-8781-725042d9bf2a)
id: miniboss_long | display_name: 笼
id: miniboss_xiaochuan | display_name: 尸兄
id: miniboss_baoguo | display_name: 宗师
id: miniboss_ma | display_name: 老板

在使用以上BOSS时我的Mod会卡死，但其他BOSS可以正常运行。

**Comment by FasciA647** [comment]
解决了，原来要用英文版对应的id

**Comment by FasciA647** [comment]
基本英文版对应的BOSS都能使用了，但是"stage_boss_gaben"还是无法使用。

**Comment by GoodCrispyShark** [comment]
stage_boss_gaben 应该可以使用 中英文都有这个id
不能使用是什么表现？

**Comment by FasciA647** [comment]
可以进入游戏，但在选择人物点击继续后会出现上面图片那样卡死。
![无标题](https://github.com/user-attachments/assets/f066066e-d27c-47b3-aecb-38b0f61657af)
另外两个最终BOSS都没有出现这种情况。

**Comment by GoodCrispyShark** [comment]
gaben的boss id是miniboss_kobe

stage_boss_gaben是localize后的id

**Comment by FasciA647** [comment]
谢谢，可以使用了。
