### ISSUE TITLE
Mod manager messed up

### ISSUE THREAD

**Issue by MajorMajorMajor6** [MemeMayhem/ModExamples#12]
What it looks like in mod manager:
![image](https://github.com/user-attachments/assets/4be3eb47-5a4d-44df-a0f2-fd557ea523a9)

How it looks like in steam workshop page:
![image](https://github.com/user-attachments/assets/3d7b4b8d-b1d3-407e-ad8f-6638bf811525)

manifest.json content:
![image](https://github.com/user-attachments/assets/3c12024a-dd67-4933-9255-20c7424f58ee)

link to mod:
https://steamcommunity.com/sharedfiles/filedetails/?id=3332037424

**Comment by fx013** [comment]
Fixed in the latest game build.
