### ISSUE TITLE
It seems that the shop cannot reroll custom relics. 商店没法刷新出自定义遗物

### ISSUE THREAD

**Issue by Penguin134** [MemeMayhem/ModExamples#120]
我通过`Api:RegisterRelic`注册了一个遗物，稀有度设置为`rare`。可是，我在游戏中的商店无法刷出这个遗物，即使我在`blocked_relics`中移除了大量游戏本体遗物，我仍无法刷新出自定义的遗物。
I registered a relic via `Api:RegisterRelic` and set the rarity to `rare`. However, I cannot spawn this relic in the in-game store, and even if I remove a large number of game relics by `blocked_relics`, I still cannot spawn my custom relic.

**Comment by fx013** [comment]
这个目前不支持，我记得 @GoodCrispyShark 说过之后会加

**Comment by GoodCrispyShark** [comment]
这周太忙了 下周找时间集中处理一下mod这边的需求

**Comment by GoodCrispyShark** [comment]
昨天的更新添加了支持
