### ISSUE TITLE
怎么做出类似蟑螂周期攻击的效果

### ISSUE THREAD

**Issue by iddsxbk** [MemeMayhem/ModExamples#122]
RegisterOnCombatDelayedCallback 这个回调可以周期触发，但是没有target参数，没法触发敌人扣血。

**Comment by fx013** [comment]
`CombatUnit:GetMainOpponent()`可以拿到target

**Comment by iddsxbk** [comment]
> `CombatUnit:GetMainOpponent()`可以拿到target

好好，问题可以关惹
