### ISSUE TITLE
Random module api. Again

### ISSUE THREAD

**Issue by AirHater** [MemeMayhem/ModExamples#123]
https://github.com/MemeMayhem/ModExamples/issues/108#issuecomment-2423588889
issue is closed and random module is still not added

**Comment by GoodCrispyShark** [comment]
How did u use it? The change should be in last friday's build

**Comment by AirHater** [comment]
![image](https://github.com/user-attachments/assets/10a8a930-2df0-4b9e-b2b1-f3eb2d5a2adc)

**Comment by GoodCrispyShark** [comment]
@ninjaaquaoutlook do you have a better insight on this?

**Comment by GoodCrispyShark** [comment]
@AirHater sorry I just double checked the build branch didn't contain the changed commit
It will be in the next release with all the new events and contest reward

**Comment by GoodCrispyShark** [comment]
Are you able to use them currently?

**Comment by SwordBacon** [comment]
It's working on my end. Glad this was added!
