### ISSUE TITLE
Api:SetCampaignBossPool breaks with certain bosses

### ISSUE THREAD

**Issue by SwordBacon** [MemeMayhem/ModExamples#124]
There are several bosses that will break the campaign pool (salad bunny, right hook, squeaker, fine dog, time traveler, chaams, butin, mars, gaven). The result is a frozen screen with no boss. I'm not sure why, maybe the IDs changed?

![image](https://github.com/user-attachments/assets/03ee7ac2-3d2d-4e65-a83e-28eb46842a98)

Also can you add boss data to the references? It would be nice to use when designing bosses of similar power level, plus we could copy them over and change their stats and dialogue.

**Comment by GoodCrispyShark** [comment]
i think some of those bosses have different IDs--since chinese and english versions have different portraits sometimes they dont share ID

**Comment by GoodCrispyShark** [comment]
could you show me which IDs are you using for them right now?

**Comment by SwordBacon** [comment]
I am using the IDs that were printed with Api:PrintBosses 

id: miniboss_sad_toad | display_name: Sadpole
id: salad_kat | display_name: Salad Bunny
id: right_hook | display_name: Right Hook
id: miniboss_pop_kat | display_name: Pop Cat
id: miniboss_screecher | display_name: Squeaker
id: miniboss_sweatsmilingface | display_name: Sweaty
id: miniboss_kideo | display_name: Kideo
id: miniboss_fine_dog | display_name: Brill Yuntiking
id: miniboss_timetraveler | display_name: TimeTraveler
id: miniboss_stone | display_name: Gymrat
id: miniboss_cheems | display_name: Chaams
id: miniboss_putin | display_name: Butin
id: miniboss_zuck | display_name: Lizardberg
id: miniboss_kodick | display_name: Goblin
id: miniboss_plasticchair | display_name: POWER
id: stage_boss_gigachad | display_name: Chad
id: stage_boss_Mars | display_name: Mars
id: stage_boss_gaben | display_name: Gaven

**Comment by SwordBacon** [comment]
I guess the ones that don't work need the chinese id?

id: miniboss_long | display_name: 笼
id: miniboss_anuodun | display_name: 阿诺顿
id: miniboss_khan | display_name: 可汗
id: miniboss_xiaochuan | display_name: 尸兄
id: miniboss_dingzhen | display_name: 王塘理
id: miniboss_sweatsmilingface | display_name: 流汗黄豆
id: miniboss_kideo | display_name: 小夫
id: miniboss_wuwukai | display_name: 五五开
id: miniboss_mrquin | display_name: 秦喵喵
id: miniboss_baoguo | display_name: 宗师
id: miniboss_jiege | display_name: 捷哥
id: miniboss_zhanlang | display_name: 战狠
id: miniboss_ma | display_name: 老板
id: miniboss_kodick | display_name: 烤迪克
id: miniboss_plasticchair | display_name: 帕瓦椅
id: stage_boss_trump | display_name: 气盛
id: miniboss_shushu | display_name: 蜀黍
id: stage_boss_gaben | display_name: G瘦

**Comment by SwordBacon** [comment]
stage_boss_gaben does not work despite it being the same ID

**Comment by SwordBacon** [comment]
apparently his actual boss id is "miniboss_kobe"

**Comment by GoodCrispyShark** [comment]
yea they real IDs are stored in MobData.lua.txt
