### ISSUE TITLE
Is there a way to dynamically change sprite like the sakiko character?

### ISSUE THREAD

**Issue by HarbingerOfCrazy** [MemeMayhem/ModExamples#127]
or poolyMorph for that matter

**Comment by GoodCrispyShark** [comment]
We will try to support it next week

**Comment by GoodCrispyShark** [comment]
This will be supported in the next update (should be end of this week)

**Comment by GoodCrispyShark** [comment]
https://github.com/MemeMayhem/ModExamples/wiki/Tutorial#change-avatar-during-battle

I have added the tutorial for this
