### ISSUE TITLE
获取属性的api获取能量回复只能获取初始值吗

### ISSUE THREAD

**Issue by iddsxbk** [MemeMayhem/ModExamples#130]
比如用combat_unit:GetBoundedAttribute("energy_per_second")这个获取能量回复值，返回的是初始设置的那个回复量，后续加成后没有变高

**Comment by GoodCrispyShark** [comment]
是当前值
如果不对应该是你前后某个地方写的出问题了，比如你获取时已经打完了或者还没开始打导致存的额外数值还没apply
