### ISSUE TITLE
Triggering a start game or an endgame

### ISSUE THREAD

**Issue by aomaooo** [MemeMayhem/ModExamples#133]
Hello, I'm trying to make a mod where I want to modify the max_energy attribute between each rounds. 
I managed to create a global function that does that, but when I restart a new game or if I lose, or win, or if I quit and make another game, my global value stays in memory, and I can't reset it's value. If I reset my value OnCombatStart or OnCombatEnd it reset my value between each fight, and that's not that I want.
I read the entire mod documentation and there is no mention of a function that I can use to detect a win, a loss or an exit off the game.
It would be great to have those trigger events on a new game, on a loss, on a win, on exiting the combat.
If it exists, have my appologies, tell me how to trigger them. If not, is there a way for me to detect those events?

**Comment by aomaooo** [comment]
If there was a round counter it would be good too, but I haven't seen a function doing that.
My idea was to count the round at the end of every fights and use this global value to increment my max_energy. So that each round my max_energy attribute is higher after each fight. But as a global value, it doesn't reset my round counter when launching a new game, because I haven't got the way to modify its value, there is no trigger events for a loss a win or exiting the game. 
So, if there is a way of detecting the actual round, it would be really helpfull for me because I won't have to detect the round number with a global function to do that, just pull the round number and use it with my function to grow the max_energy, it would solve all my problems.

**Comment by aomaooo** [comment]
I finally managed to do what I wanted to do in a different way.

If there was a way to retrieve the current wave number, it would have been a lot easier. But I still don't know if this feature is available. It would be nice.

**Comment by GoodCrispyShark** [comment]
you can get the wave number from hero.run_instance.wave

**Comment by aomaooo** [comment]
Thank you for the tip!
