### ISSUE TITLE
Can't print any log

### ISSUE THREAD

**Issue by CookieAlien** [MemeMayhem/ModExamples#134]
After December 17th I can't get any log to print, either using `Api:Log` or prints such as `Api:PrintCharacters()`, I also used `Api:EnableLog(true)` but still didn't print any logs

I digged through player.log and saw `Script logging is disabled because of release build configuration. Check Scenes/BuildInfo.` in the log, so an update might have caused this?

**Comment by GoodCrispyShark** [comment]
Thanks for the report! Let us check

**Comment by GoodCrispyShark** [comment]
The log seems working, its just the Mod Manager seems to lead you to the wrong mod folder position sometimes (we are fixing that)
Did it bring you to `AppData\LocalLow\Cr3 Studio\Meme Mayhem\Mods`? this is the wrong place and does not have the correct log
Could you try to go to `SteamLibrary\steamapps\workshop\content\2719030`? this should be the right place

**Comment by CookieAlien** [comment]
I found the logs now, but it's weird that it's in the workshop folder, because my mod that's trying to printing logs has not uploaded yet, also I don't think the workshop folder is a good place to put log files in

**Comment by GoodCrispyShark** [comment]
did u copy a existing mod? is it possible that it's sharing the same mod id with a subscribed mod?

**Comment by CookieAlien** [comment]
I didn't copy an entire mod (maybe some code but not fully) and I don't think there is a mod with the same id

**Comment by CookieAlien** [comment]
It looks like if I enable any mod from the workshop, the log would be at workshop folder, and after I disabled all workshop mods, the log went back to local mod folder

**Comment by GoodCrispyShark** [comment]
this will be fixed in the next update

**Comment by GoodCrispyShark** [comment]
Just updated, please make sure your game version is 0.22.34
Let me know if this problem persists!
