### ISSUE TITLE
有没有办法做到像游戏里客服小祥一样打到一定的关卡后自动切换人物形象图片

### ISSUE THREAD

**Issue by a3662981** [MemeMayhem/ModExamples#14]
有没有办法做到像游戏里客服小祥一样打到一定的关卡后自动切换人物形象图片

**Comment by MajorMajorMajor6** [comment]
这个目前没有mod api支持。

**Comment by fuxiao1563** [comment]
> 这个目前没有mod api支持。

如果可以的话，希望自定义boss也能够实现这个功能

**Comment by GoodCrispyShark** [comment]
https://github.com/MemeMayhem/ModExamples/wiki/Tutorial-zh_CN#%E5%9C%A8%E6%88%98%E6%96%97%E4%B8%AD%E6%9B%B4%E6%8D%A2%E8%A7%92%E8%89%B2%E5%BD%A2%E8%B1%A1

添加了支持，教程在这
