### ISSUE TITLE
多个Attribute相关问题

### ISSUE THREAD

**Issue by helihydrogen** [MemeMayhem/ModExamples#15]
1：PerkQuest计数器当前是否允许在属性栏中显示？
在提供的实例中PerkQuest计数是以文本形式弹出显示的，但这种实现方法对画面的干扰较强。不幸的是我没有找到能够在属性栏里显示额外属性的实例。
2：目前是否有办法引用存款及商店折扣的数值？
同样的，Attribute列表中也没有相关的属性。

**Comment by fx013** [comment]
自定义角色属性显示计数的功能在今天的版本里会加上。

**Comment by helihydrogen** [comment]
感谢回复。那么人物存款还有商店折扣的数值修改呢？目前有实现办法吗？AddGold方法无法实现负修改。

**Comment by MajorMajorMajor6** [comment]
0.20.133 中增加了新的Api;GetGold()

https://github.com/MemeMayhem/ModExamples/blob/main/Advanced-Mod2/additions/scripts/Trigger.lua.txt#L225

**Comment by MajorMajorMajor6** [comment]
@GoodCrispyShark SetGold不允许负值？

**Comment by MajorMajorMajor6** [comment]
自定义属性的例子如下（需要新版本0.20.133）：https://github.com/MemeMayhem/ModExamples/blob/main/Basic-NewAttribute/additions/scripts/Trigger.lua.txt

**Comment by helihydrogen** [comment]
感谢回复！希望后续能够进一步实现商店价格倍率（折扣）修改以及不获得欠债神器下的负存款实现。
