### ISSUE TITLE
给敌人施加debuff或者dot伤害

### ISSUE THREAD

**Issue by yangjiandendi** [MemeMayhem/ModExamples#16]
请问可以出一个Perk的例子，能给敌人施加一些debuff或者dot伤害。 

比如说：每用石头攻击10次，施加一层流血。流血伤害为每秒一次的持续伤害，每层流血初始伤害为1，每过一秒增加数值为当前层数的伤害。最多可叠加10层。

**Comment by NinjaAqua445** [comment]
您好，每秒dot伤害可以用 `combat_unit:RegisterOnCombatPeriodicCallback(name, function(level, time)` 实现
调用方式参考：
https://github.com/MemeMayhem/ModExamples/blob/0becad76956dda1240d36e7d056b4f8af7fe1441/Advanced-Mod2/additions/scripts/Trigger.lua.txt#L208

**Comment by GoodCrispyShark** [comment]
RegisterOnCombatPeriodicCallback比较costy，如果你想做先辈这种很多层的流血可以直接做一个改属性的behavior，直接降回血

**Comment by yangjiandendi** [comment]
> RegisterOnCombatPeriodicCallback比较costy，如果你想做先辈这种很多层的流血可以直接做一个改属性的behavior，直接降回血

嗯，我目前是在用这个方法做。但还是有一些问题：我无法获取当前的debuff层数。我想做一个和debuff层数相关的伤害机制。

**Comment by fx013** [comment]
@NinjaAqua445 能帮忙回答一下上面关于怎么获取debuff层数的问题吗？

**Comment by NinjaAqua445** [comment]
您好，如果您是通过behavior来实现伤害的没那么可以直接使用`PerkBehaviorSystem:GetPerkBehaviorStackCount(combat_unit, name)`来获得这个behavior的层数。
