### ISSUE TITLE
mod可以支持`js`语言吗？

### ISSUE THREAD

**Issue by scgm0** [MemeMayhem/ModExamples#17]
话说现在的`lua`为什么需要`.txt`后缀，怪怪的

**Comment by MajorMajorMajor6** [comment]
目前没有人力去支持js

**Comment by fx013** [comment]
游戏本体是用Lua实现的，目前没有办法支持其他的语言调用。

`.txt`后缀是因为我们用的Unity引擎没法识别`.lua`为文本文件，游戏里的Lua文件都是以`.lua.txt`结尾的，Mod就直接用一样的了。
