### ISSUE TITLE
[Wiki] Add doc containing hook list

### ISSUE THREAD

**Issue by heartskingu** [MemeMayhem/ModExamples#18]
I feel like there is an important doc misssing, there isn't a place listing the possible trigger hooks (like on missile hit/dodge). I'm trying to create a self hit missile that heals the player, but I can't find any example in here that would provide me the required information

(super easy to mod basic stuff using in-game assets btw, congrats)

**Comment by yangjiandendi** [comment]
https://github.com/MemeMayhem/ModExamples/blob/main/Basic-NewMissile/additions/scripts/Trigger.lua.txt

here you can find an example for a self hit missile that heals the player

**Comment by heartskingu** [comment]
omg I totally missed the "target_self = true,". Thank you so much <3

**Comment by heartskingu** [comment]
closed
