### ISSUE TITLE
例子里的难度mod有bug

### ISSUE THREAD

**Issue by a3662981** [MemeMayhem/ModExamples#19]
吧例子里的难度控制mod代码复制到我的mod里后，mod怪物属性确实有变化，但如果先玩mod然后去正常模式玩，正常模式的怪也会受到难度mod的影响

**Comment by MajorMajorMajor6** [comment]
感谢指出，这个将在下一个版本 0.20.133 中修复。
之前的Api:SetCampaignDifficulty(mod_difficulty)会被淘汰，继续使用只有错误提示和日志提示，没有效果。请使用Api:SetCampaignEnemySettings(character_id, mod_difficulty), 新的Api只会修改指定角色的难度
