### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by alejandroch495** [MemeMayhem/ModExamples#2]
Should have a list of variables/attributes that missiles can have along with relics, and perks. This would help better identify what can and cant be done.

**Comment by KingofApples** [comment]
Agree with alejandroch. Feels like my hands are tied making mods right now. No idea what I can actually do and no clue how to reference anything. I assume what's inside the mod examples is probably under 2% of what is actually possible. Really need some type of list or table with this information, or some way to access it

**Comment by fx013** [comment]
@alejandroch495 @KingofApples Thanks for the suggestion. I have added Wiki pages listing all the [Characters](https://github.com/MemeMayhem/ModExamples/wiki/Characters), [Attributes](https://github.com/MemeMayhem/ModExamples/wiki/Attributes), [Perks](https://github.com/MemeMayhem/ModExamples/wiki/Perks), [Relics](https://github.com/MemeMayhem/ModExamples/wiki/Relics), [Bosses](https://github.com/MemeMayhem/ModExamples/wiki/Bosses) and [Choices](https://github.com/MemeMayhem/ModExamples/wiki/Choices).

In case the lists become out-of-date, you can generate up-do-date list info using mod APIs listed at the end of the Advanced-Mod1 example: https://github.com/MemeMayhem/ModExamples/blob/main/Advanced-Mod1/additions/scripts/Trigger.lua.txt#L319-L325 . They will output the info into a .txt file in the `Mods` folder.

**Comment by KingofApples** [comment]
Exactly what I wanted. TYSM!
