### ISSUE TITLE
 需要更多caster/target 的钩子函数 

### ISSUE THREAD

**Issue by lizncu111** [MemeMayhem/ModExamples#20]

**Comment by fx013** [comment]
@NinjaAqua445 可以帮忙给这个加个Wiki吗？

**Comment by NinjaAqua445** [comment]
已添加常用函数列表Wiki页面。
[CombatUnit Methods](https://github.com/MemeMayhem/ModExamples/wiki/CombatUnit-Methods-zh_CN)
[AttackManager Methods](https://github.com/MemeMayhem/ModExamples/wiki/AttackManager-Methods-zh_CN)
