### ISSUE TITLE
关于叠BUFF的一些提问

### ISSUE THREAD

**Issue by MiikuCry** [MemeMayhem/ModExamples#21]
作者您好，非常喜欢您的游戏，所以我正在按照您的教程制作MOD。
叠甲：本人代码水平是焚书坑儒级别，只能看懂一些基础的，剩下只会按照教程里的内容设置。LUA也在此前完全没有接触过。
以下是我遇到的问题：
1. 请问作者，MOD中制作的子弹，是只能发射出去攻击对面吗？我想做一个类似肌肉和音符这种，命中自己可以叠BUFF的子弹，可以实现吗？有看到教程里是 damage = function(attack_data, caster) 可以调用别的什么来实现嘛？
2. 因为本人真的很喜欢叠BUFF，像“努力锻炼”这种能力，我想要制作一个，或者我想作为一个初始神器赋予我的角色，在我的角色发射一个自己的子弹后可以增加这个计数，在某个计数以上和以下有不同效果，类似于低中高血糖的设计，可以实现吗？
3. 目前我设计的角色希望在达成特定条件后更换贴图，请问这个可以实现吗？

感谢作者百忙之中查看我这种比较小白的问题，希望游戏越来越好！！！

**Comment by NinjaAqua445** [comment]
您好，
1. 向自己发射的子弹需要在注册子弹数据的时候加上 `target_self = true`。调用方式参考： https://github.com/MemeMayhem/ModExamples/blob/0becad76956dda1240d36e7d056b4f8af7fe1441/Basic-NewMissile/additions/scripts/Trigger.lua.txt#L29
2. 计数器可以用 `attribute` 实现。调用方式参考： https://github.com/MemeMayhem/ModExamples/blob/main/Medium-PerkQuest/additions/scripts/Trigger.lua.txt
3. 目前没有对切换角色贴图的支持。 详细请见： https://github.com/MemeMayhem/ModExamples/issues/14

**Comment by fx013** [comment]
今天的游戏更新会加上角色自定义属性的功能，有它之后就可以用来显示计数器了。

**Comment by MajorMajorMajor6** [comment]
自定义属性的例子如下（需要新版本0.20.133）：https://github.com/MemeMayhem/ModExamples/blob/main/Basic-NewAttribute/additions/scripts/Trigger.lua.txt

**Comment by MiikuCry** [comment]
谢啦！今天晚上我再研究学习一下！！

MajorMajorMajor6 ***@***.***> 于 2024年9月19日周四 14:16写道：

**Comment by yangjiandendi** [comment]
> 自定义属性的例子如下（需要新版本0.20.133）：https://github.com/MemeMayhem/ModExamples/blob/main/Basic-NewAttribute/additions/scripts/Trigger.lua.txt

这个应该怎么实现像忍者那样的  0/7 的进度，然后进度满了之后重新计数？

**Comment by MajorMajorMajor6** [comment]
@yangjiandendi 需要你自己检测属性值达到了最大值，然后重置为0

**Comment by MiikuCry** [comment]
@NinjaAqua445 @MajorMajorMajor6 @fx013 请问各位老师们，咱们现在捅咕捅咕，游戏的mod界面变成这样子了
![屏幕截图 2024-09-20 155458](https://github.com/user-attachments/assets/c9e272d9-bb37-4275-826c-706f588d6af7)
请问这是什么毛病啊？是我代码里全是错误吗wwww
另外请问咱们游戏里面有没有mod报错文档之类的，咱们代码学的太烂了，想破头都不知道哪里出问题了OWO

**Comment by fx013** [comment]
@MiikuCry 这种加载异常一般是代码里有错误导致的，看一下这里的Troubleshooting guide: https://github.com/MemeMayhem/ModExamples/wiki/Troubleshooting#what-if-the-game-gets-stuck-at-the-loading-screen-or-is-totally-broken  ，找到Player.log看看里面有什么样的exception，里面会有文件和行号信息帮助定位问题在哪。如果弄不明白可以把Player.log发上来我们看看，或者把你的Mod打包发上来看看。

**Comment by fx013** [comment]
@yangjiandendi 可以参见这个石头击中30次增加一个石头的例子：https://github.com/MemeMayhem/ModExamples/tree/main/Medium-PerkQuest

**Comment by MiikuCry** [comment]
> @MiikuCry 这种加载异常一般是代码里有错误导致的，看一下这里的Troubleshooting guide: https://github.com/MemeMayhem/ModExamples/wiki/Troubleshooting#what-if-the-game-gets-stuck-at-the-loading-screen-or-is-totally-broken ，找到Player.log看看里面有什么样的exception，里面会有文件和行号信息帮助定位问题在哪。如果弄不明白可以把Player.log发上来我们看看，或者把你的Mod打包发上来看看。

谢谢大佬，我再研究研究！！
