### ISSUE TITLE
获取敌方的属性应该怎么办

### ISSUE THREAD

**Issue by a3662981** [MemeMayhem/ModExamples#22]
现在可以获取自己属性根据自己属性的百分比决定子弹伤害，但如果想根据敌方最大生命百分比决定子弹伤害的话应该怎么办

**Comment by MajorMajorMajor6** [comment]
可以先在子弹设置中把伤害设置为0， 然后用这个钩子函数来得到敌方（target）的最大生命，并对其造成百分比伤害

https://github.com/MemeMayhem/ModExamples/blob/main/Advanced-Mod2/additions/scripts/Trigger.lua.txt#L104

**Comment by fx013** [comment]
对，按照 @MajorMajorMajor6 说的方法，可以用一个relic注册子弹命中的回调，然后在回调里来计算伤害。回调里的caster是自己，target是敌人。属性API参见https://github.com/MemeMayhem/ModExamples/wiki/CombatUnit-Methods-zh_CN
