### ISSUE TITLE
在改变子弹图形后游玩mod角色被锁了

### ISSUE THREAD

**Issue by clepidstar** [MemeMayhem/ModExamples#23]
按说明改完两个.json并在脚本加了 missile = DCEI.SimpleUnit("COMBAT Missile My Powerful Rock"),后进入游戏显示角色需要客服小祥通关14波后解锁，但我的小祥已经通关过了，并且再次打完14波后仍不能正常解锁

**Comment by fx013** [comment]
这种一般是因为mod里有错误导致的加载异常。再仔细对照一下教程看是不是哪里写错了。如果还是解决不了，你可以把你当前的Mod文件打包发上来我们看看。

**Comment by clepidstar** [comment]
> 这种一般是因为mod里有错误导致的加载异常。再仔细对照一下教程看是不是哪里写错了。如果还是解决不了，你可以把你当前的Mod文件打包发上来我们看看。

感谢回复！找不到错误删了从头写解决了。
