### ISSUE TITLE
眩晕效果

### ISSUE THREAD

**Issue by yangjiandendi** [MemeMayhem/ModExamples#25]
请问有没有方法可以给自己和敌人施加眩晕效果？
比如一个遗物：在发射20个子弹后眩晕自己3秒。

**Comment by NinjaAqua445** [comment]
您好，晕眩是通过 `perk behavior` 实现的。
例如，您可以构建如下晕眩3秒的能力：
```lua
{
    id = "debuff_stun_3s",
    display_name = "Stun for 3 seconds",
    behavior = {
        description = DCEI.GetTranslationText("combat/behavior/stun_on_start/description"),
        buff_bar_icon = DCEI.Texture("flat_icon_emoji_dizzy_1f4ab_ipick"),
        actor_event_on_apply = "EventStunOn",
        actor_event_on_remove = "EventStunOff",
        interval = 3, -- stun for 3 s
        interval_effect = {
            stun = true,
        },
    },
},
```
之后使用 `ApplyPerkBehavior` API添加即可。类似的例子可见：https://github.com/MemeMayhem/ModExamples/blob/fc818412e6038c0bf9617c40efcdf1c78925cf9c/Basic-NewPerk/additions/scripts/Trigger.lua.txt#L33
例子中使用的是 `Api.PerkBehaviorSystem:ApplyPerkBehaviorToSelf(target, name, stack_count, extra_time)`，我们也提供了 `Api.PerkBehaviorSystem:ApplyPerkBehavior(target, caster, name, stack_count, extra_time)`

**Comment by yangjiandendi** [comment]
> 您好，晕眩是通过 `perk behavior` 实现的。 例如，您可以构建如下晕眩3秒的能力：
> 
> ```lua
> {
>     id = "debuff_stun_3s",
>     display_name = "Stun for 3 seconds",
>     behavior = {
>         description = DCEI.GetTranslationText("combat/behavior/stun_on_start/description"),
>         buff_bar_icon = DCEI.Texture("flat_icon_emoji_dizzy_1f4ab_ipick"),
>         actor_event_on_apply = "EventStunOn",
>         actor_event_on_remove = "EventStunOff",
>         interval = 3, -- stun for 3 s
>         interval_effect = {
>             stun = true,
>         },
>     },
> },
> ```
> 
> 之后使用 `ApplyPerkBehavior` API添加即可。类似的例子可见：
> 
> https://github.com/MemeMayhem/ModExamples/blob/fc818412e6038c0bf9617c40efcdf1c78925cf9c/Basic-NewPerk/additions/scripts/Trigger.lua.txt#L33
> 
> 
> 例子中使用的是 `Api.PerkBehaviorSystem:ApplyPerkBehaviorToSelf(target, name, stack_count, extra_time)`，我们也提供了 `Api.PerkBehaviorSystem:ApplyPerkBehavior(target, caster, name, stack_count, extra_time)`




非常感谢！
