### ISSUE TITLE
请问为什么我在mod在mod管理器里显示了，但是游戏里加载不出来呢？

### ISSUE THREAD

**Issue by zhucegemaoari** [MemeMayhem/ModExamples#26]
请问为什么我在mod在mod管理器里显示了，但是游戏里加载不出来呢？
我尝试清空script里的内容，复制了教程里的，依然是mod管理器显示，游戏里无法加载

**Comment by MajorMajorMajor6** [comment]
看看mod日志？

**Comment by zhucegemaoari** [comment]
> 看看mod日志？

我搞定了，我把例子里的加号也复制到脚本里了- -。请问大佬方便提供一些傻瓜版的教程吗，比如如何设定石头的攻击力根据力量来而不是固定200啊，我没有编程基础，只能勉强看懂一些不是很复杂的例子

**Comment by MajorMajorMajor6** [comment]
https://github.com/MemeMayhem/ModExamples/blob/main/Basic-NewMissile/additions/scripts/Trigger.lua.txt#L16

**Comment by zhucegemaoari** [comment]
> https://github.com/MemeMayhem/ModExamples/blob/main/Basic-NewMissile/additions/scripts/Trigger.lua.txt#L16

谢谢，我有空学习一下
