### ISSUE TITLE
难度调整mod只对小怪有效

### ISSUE THREAD

**Issue by a3662981** [MemeMayhem/ModExamples#27]
难度调整mod用了后参数每个都调过了，都只改变小怪的属性，boss生命值没变化

**Comment by MajorMajorMajor6** [comment]
游戏本体中，boss的属性和enemy_settings无关。只和星数（ascension level）有关。你也可以依照这个例子修改boss的强度：https://github.com/MemeMayhem/ModExamples/blob/main/Basic-NewBoss/additions/scripts/Trigger.lua.txt
