### ISSUE TITLE
如何修改mod角色的能力包池子

### ISSUE THREAD

**Issue by Nagasoyo** [MemeMayhem/ModExamples#29]
有没有办法删减原版的能力包池子，我在教程似乎只能添加新的能力包，剩下的都是原本那个角色包。原来的角色的能力包池子有许多不许要的能力包，我希望能够排除一部分不需要的卡包，以至于我添加多个能力包之后不会导致随机性太强，游戏体验差

**Comment by Nagasoyo** [comment]
还有，能不能做到开局给予能力包啊，我看似乎只有神器和表情的开局修改，我想开局给予组建乐队这一能力卡，但并没用找到什么好的办法

**Comment by iddsxbk** [comment]
很怪，乐队初始没法加，但是忍者进度是可以开局加的，复制人id设成箱子也没用，是不是哪里要加开关这种

**Comment by NinjaAqua445** [comment]
您好，想要从能力池子里去掉某些能力卡只需要在character data里加上 `blocked_perks` 即可。
例如从角色的能力卡池里去点石头卡：
```lua
blocked_perks = {
    "attack_rock",
},
```
同理，想要从神器池子里去掉某些神器，只需要在character data里加上 `blocked_relics` 即可。
想要开局给与角色特定的能力卡只需要在character data里加上 `perks` 即可。
例如开局给角色组建乐队：
```lua
perks = {
    "recruit_band_quest",
},
```

**Comment by Nagasoyo** [comment]
Api:CopyCharacter("naysayer", {
        id = "my_character",
        display_name = "第一个Mod角色",
        short_description = "这是我第一个mod创建的角色。",
        icon = DCEI.Texture("my_character_small"),
        icon_low_resolution = DCEI.Texture("my_character_small"),
        icon_high_resolution = DCEI.Texture("my_character_large"),
        unit = DCEI.Unit("COMBAT Unit First Mod Character"),
+       attack_ids = {
+           "my_power_rock",
+           "my_power_rock",
+       },
    })
  character date指的是这里面的内容吗，本人对编程只有c语言的一点点基础，基本都是靠教程解决问题的。。。

**Comment by NinjaAqua445** [comment]
> Api:CopyCharacter("naysayer", { id = "my_character", display_name = "第一个Mod角色", short_description = "这是我第一个mod创建的角色。", icon = DCEI.Texture("my_character_small"), icon_low_resolution = DCEI.Texture("my_character_small"), icon_high_resolution = DCEI.Texture("my_character_large"), unit = DCEI.Unit("COMBAT Unit First Mod Character"),
> 
> * ```
>     attack_ids = {
>   ```
> * ```
>         "my_power_rock",
>   ```
> * ```
>         "my_power_rock",
>   ```
> * ```
>     },
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   })
>   character date指的是这里面的内容吗，本人对编程只有c语言的一点点基础，基本都是靠教程解决问题的。。。

是的，用教程举例子就是在教程的代码中添加如下内容：
```lua
Api:CopyCharacter("naysayer", {
        id = "my_character",
        display_name = localization_table["character/my_character/display_name"],
        short_description = localization_table["character/my_character/short_description"],
        icon = DCEI.Texture("my_character_small"),
        icon_low_resolution = DCEI.Texture("my_character_small"),
        icon_high_resolution = DCEI.Texture("my_character_large"),
        unit = DCEI.Unit("COMBAT Unit First Mod Character"),
        relics = {
            "my_power_cookie",
        },
        perks = {
            "recruit_band_quest", --- 给角色添加组建乐队能力牌作为初始能力牌
        },
        blocked_perks = {
            "attack_rock", ---从能力池中去掉石头能力牌
        },
        attack_ids = {
            "my_power_rock",
            "my_power_rock",
        },
        perk_chains = {
            {
                "my_power_perk",
                "small_rock_on_power_rock",
            },
            {
                "gain_attack",
                "attack_quest",
                "damage_to_health",
                "flex_on_flex",
            },
        },
    })
```

**Comment by Nagasoyo** [comment]
非常感谢
