### ISSUE TITLE
我该如何获取详细的API？

### ISSUE THREAD

**Issue by LasonbrahZH** [MemeMayhem/ModExamples#3]
想要设计复杂的效果必然离不开调用原版的函数和属性，但问题在于example中仅展示了一些基础的函数。比如我希望子弹的伤害和“运气”属性挂钩，我该从什么地方调用该属性呢？如果我想要给属性面板上加上自己的图标，类似“偷窃训练进度0/7”产生的图标，我又该调用什么函数呢？
所以我认为需要一张详细的API手册或者是表单之类的，好让模组创作者查询。

**Comment by fx013** [comment]
谢谢建议，另一个issue里也提到同样的问题。我的想法是把游戏里的实现尽量多的发布出来给大家参考，但是因为游戏本体并不是用mod API做的，需要一些调整才能发布，可能会优先发布有人问到的。

你问的第一个问题我在另一个issue里也解答了一下：https://github.com/MemeMayhem/ModExamples/issues/4 。 有个API `caster:GetBoundedAttribute()`可以获取角色任意属性。属性列表可以参看：https://github.com/MemeMayhem/ModExamples/wiki/Attributes-zh_CN

第二个问题更复杂一些，我和团队其他成员讨论一下看能不能找一个游戏里的例子公布出来。

API手册也在考虑。但是因为游戏大部分实现都是Lua（而且没啥注释），现在还没有办法直接生成API手册。可能得等以后人手更充足的时候才能做了。

**Comment by LasonbrahZH** [comment]
> 谢谢建议，另一个issue里也提到同样的问题。我的想法是把游戏里的实现尽量多的发布出来给大家参考，但是因为游戏本体并不是用mod API做的，需要一些调整才能发布，可能会优先发布有人问到的。
> 
> 你问的第一个问题我在另一个issue里也解答了一下：#4 。 有个API `caster:GetBoundedAttribute()`可以获取角色任意属性。属性列表可以参看：https://github.com/MemeMayhem/ModExamples/wiki/Attributes-zh_CN
> 
> 第二个问题更复杂一些，我和团队其他成员讨论一下看能不能找一个游戏里的例子公布出来。
> 
> API手册也在考虑。但是因为游戏大部分实现都是Lua（而且没啥注释），现在还没有办法直接生成API手册。可能得等以后人手更充足的时候才能做了。

非常感谢，如果有大量的参考可用，确实会有很大的帮助。那我就静候佳音了。
另外，请问官方有没有Discord以外的群聊，国内使用discord实在是非常麻烦，我尝试了不同的魔法也只得到了“无法接受邀请”的结果。

**Comment by fx013** [comment]
我加了一个新的例子，第10次石头攻击获得一个额外的石头：https://github.com/MemeMayhem/ModExamples/blob/main/Medium-PerkQuest/additions/scripts/Trigger.lua.txt

现在还没有办法显示击中次数，需要加新的mod API来自定义custom attribute，我们这周会加上（需要新游戏版本）。

目前modding技术支持只在这个github repo有，discord上有modding问题也会转到这里来。如果你有modding相关问题，都可以在这里问。

**Comment by fx013** [comment]
@LasonbrahZH 现在已经支持自定义角色属性了，我更新了例子用自定义属性显示石头命中次数：https://github.com/MemeMayhem/ModExamples/tree/main/Medium-PerkQuest

另外我们还在repo加入了一部分游戏的源代码供大家参考：https://github.com/MemeMayhem/ModExamples/tree/main/References
