### ISSUE TITLE
GameMechanicTags.lua.txt references wraith.

### ISSUE THREAD

**Issue by mbomb007** [MemeMayhem/ModExamples#31]
https://github.com/MemeMayhem/ModExamples/blob/main/References/GameMechanicTags.lua.txt

This perk was renamed to Wrath. Is it still `wraith` behind the scenes?

```
    wraith = GameMechanicTags.ATTACK_SIZE
        .. "<sprite name=angry_1f621>"
        .. "</size><color=#00acee>"
        .. ("combat/tag/wraith/name")
        .. "</color>",
```

and

```
wraith_on_explosion = GameMechanicTags.ATTACK_SIZE .. "<sprite name=smh_wraith_on_explosion></size>",
```

**Comment by MajorMajorMajor6** [comment]
yes, it's still `wraith` behind the scene.

**Comment by GoodCrispyShark** [comment]
yes. apologize for my typo. its too much effort to change all the reference in all the scripts and might cause bugs
