### ISSUE TITLE
[Suggestion] combat_unit:RegisterOnAttributeModifyCallback

### ISSUE THREAD

**Issue by heartskingu** [MemeMayhem/ModExamples#35]
It'd be great to have an "RegisterOnAttributeModifyCallback" for creating new triggers based on stats. As a dumb example, a relic that doubles your strength bonus. Currently Api:RunCombatOnlyTimer allows us for creating custom triggers, like "if strength >= X", but it's not posssible to update "incoming" buffs values to be doubled

**Comment by NinjaAqua445** [comment]
Hi, we do have an API called `RunRegisterOnSetAttributeCallback`. You can use it like this:
```lua
combat_unit:RegisterOnSetAttributeCallback(name, function(level, attribtue, old_value, new_value)
        -- do what you want
    end
end)
```
[Wiki](https://github.com/MemeMayhem/ModExamples/wiki/CombatUnit-Methods)

**Comment by heartskingu** [comment]
Thanks @NinjaAqua445, I'm sorry, I've been using the examples as a doc and didn't check the Wiki. I'll make sure to double check it next time :) Thanks for the fast response
