### ISSUE TITLE
Document the Mods folder path in Proton installations

### ISSUE THREAD

**Issue by mbomb007** [MemeMayhem/ModExamples#36]
https://github.com/MemeMayhem/ModExamples/wiki/Tutorial#create-a-mod

> To create a new mod, simply create a new folder under `%USERPROFILE%\AppData\LocalLow\Cr3 Studio\Meme Mayhem\Mods` and add the necessary files. If the Mods folder does not exist, create it first.

The path given above is for Windows. Add documentation for users that play using Proton on Linux.

The path would be `~/.steam/steam/steamapps/compatdata/2719030/pfx/drive_c/users/steamuser/AppData/LocalLow/Cr3 Studio/Meme Mayhem/Mods`

**Comment by GoodCrispyShark** [comment]
@fx013 should we put this in document and close the issue?

**Comment by fx013** [comment]
I have updated tutorial to reference this issue.
