### ISSUE TITLE
I can't figure out how to play a mod that I'm making

### ISSUE THREAD

**Issue by mbomb007** [MemeMayhem/ModExamples#37]
I am working to create a mod. I open the mod manager with Ctrl + F8, per the [tutorial](https://github.com/MemeMayhem/ModExamples/wiki/Tutorial). I can see my mod's files in the correct location.

How do I play with my mod? When I click Play With Mods, there are no mods. I tried uploading the mod to Steam, then Subscribing to it, but still no mods show up.

[log-2024-09-19-21-04-39.txt](https://github.com/user-attachments/files/17068847/log-2024-09-19-21-04-39.txt)

**Comment by MajorMajorMajor6** [comment]
you need to add a character, then you should be able to see it in the character selection page.

**Comment by MajorMajorMajor6** [comment]
share your mod with me if you have added a character but still couldn't see it. are you using linux?
