### ISSUE TITLE
增加初始能力牌后mod界面看不到角色了

### ISSUE THREAD

**Issue by Nagasoyo** [MemeMayhem/ModExamples#39]
这是加载日志和代码，按教程添加了初始能力牌，然后在角色界面就看不到角色了。。什么都没显示
([log-2024-09-20-18-24-30.txt](https://github.com/user-attachments/files/17073693/log-2024-09-20-18-24-30.txt))

[Trigger.lua.txt](https://github.com/user-attachments/files/17073704/Trigger.lua.txt)

**Comment by NinjaAqua445** [comment]
您好，这应该是您代码中第13行 `"attack_brain"` 结尾没有加上 `,` 导致的语法错误。加上后即可正常显示。
![image](https://github.com/user-attachments/assets/47a5b6e5-4351-4f71-bdf1-b65766c4e3e9)
建议您在您的编辑器里添加lua插件并且将 `.lua.txt` 后缀关联到lua文件，这样类似的语法错误就会很好避免了。

**Comment by Nagasoyo** [comment]
真的是这个原因。。。我是用的vscode，似乎并不会提示缺少，   现在已经解决了
