### ISSUE TITLE
金币数量改变的回调函数无法使用

### ISSUE THREAD

**Issue by lizncu111** [MemeMayhem/ModExamples#40]
![OSV8IVUFR~ZP3ZO{TN@9FTN](https://github.com/user-attachments/assets/40cbdfd6-22c7-4d1e-89a5-7165392a8f9a)

**Comment by helihydrogen** [comment]
这个回调函数针对的场景是消费金币（金币减少）

金币修改是这个：

> ---@param callback fun(level, current_gold)
> CombatUnit:RegisterOnPlayerGoldChangeCallback(perk_or_relic_name, callback)
