### ISSUE TITLE
Struggling with print commands

### ISSUE THREAD

**Issue by Jonathan-Hollingsworth** [MemeMayhem/ModExamples#41]
I'm currently attempting to use `Api:PrintPerks()` to learn about how the `shark_group` perk works so I can use it an inspiration for a custom perk, but the log is nowhere to be seen no matter how I try to use the command.

Is there something that I am missing?

**Comment by GoodCrispyShark** [comment]
i think this is because shark_group doesn't have it's own function/use callbacks
there are 3 ways to get shark in game right now (common shark, shark relic and shark quest) and when players get them we did a shark_group check
probably you could print those 3 perk/relic instead

**Comment by MajorMajorMajor6** [comment]
https://github.com/MemeMayhem/ModExamples/wiki/Tutorial#learn-more-about-meme-mayhem-moddinghttps://github.com/MemeMayhem/ModExamples/wiki/Tutorial#learn-more-about-meme-mayhem-modding

> We also provide a set of APIs to retrieve data used in the base game, allowing mode developers to reuse them. The following APIs will print data to the log, which is stored in the mods' root directory (Press Ctrl + F8, then click "Open local mods folder").

**Comment by MajorMajorMajor6** [comment]
print result will look like: https://github.com/MemeMayhem/ModExamples/wiki/Perks . 
if you want to know the implementation details of `shart_group`, you should directly ask @GoodCrispyShark. we did plan to release some internal code, mainly how we implemented perks and relics in the near future

**Comment by fx013** [comment]
@Jonathan-Hollingsworth You can find all perk data and some implementation examples in the reference folder: https://github.com/MemeMayhem/ModExamples/tree/main/References . They are from the actual game, though incomplete.
