### ISSUE TITLE
CombatUnit:GetPerks() 被战斗环节相关钩子函数触发时会造成对应战斗环节产生死循环

### ISSUE THREAD

**Issue by helihydrogen** [MemeMayhem/ModExamples#42]
其余钩子函数尚未测试

**Comment by MajorMajorMajor6** [comment]
只是GetPerks吗？代码一眼看上去只读的话不该有问题。
能把你的钩子函数贴出来吗？

**Comment by helihydrogen** [comment]
测试代码：
```
function(combat_unit)
        combat_unit:RegisterOnCombatEndCallback("custom_perk", function(level)
            --[[ Api:log("print type".. type(combat_unit:GetPerks())) ]]
            Api:log("print list".. table.concat(combat_unit:GetPerks(),","))
        end)
    end)
```

已知combatend：会使游戏无法进入三选一
beforecombatstart和combatstart：敌机会循环加载垃圾话，一定时间后停止加载，背景音乐在一定时间后开始卡顿，双方不会发射任何子弹，大招在能量槽满后会触发一次但不正常发射，第二次大招槽满后不会触发任何事件。

**Comment by fx013** [comment]
@helihydrogen GetPerks和Api:Log要这样用：

```lua
for perk, count in pairs(combat_unit:GetPerks()) do
    Api:Log("Perk " .. perk .. " = " .. count)
end
```

注意是大写"L"，你的代码里调用了一个不存在的函数导致游戏逻辑中断了。查mod问题的时候你可以找到`Player.log`看看里面有没有error log，参见：https://github.com/MemeMayhem/ModExamples/wiki/Troubleshooting#what-if-the-game-gets-stuck-at-the-loading-screen-or-is-totally-broken

combat_unit:GetPerks()返回的是key/value table，不是array，不能用table.concat。你可以用`pairs`遍历，或者直接查询哪个perk有几个：`local count = perks[perk_name] or 0`
