### ISSUE TITLE
角色基础属性的修改

### ISSUE THREAD

**Issue by Nagasoyo** [MemeMayhem/ModExamples#43]
我在教程和给的几个示例代码中似乎都没有看到角色基础属性如何修改，可能advanced2里面有，但是有点太长了。。看不懂，本人基本没有编程基础，代码长一点就非常吃力，而且代码并没有注释，能力卡和神器配合ai稍微能懂一点，但advancedmod2的着实太长了

**Comment by fx013** [comment]
基础属性的修改可以参考这个例子：https://github.com/MemeMayhem/ModExamples/blob/main/Medium-PerkQuest/additions/scripts/Trigger.lua.txt#L28-L35 。这个例子战斗开始时增加临时生命上限1000，在战斗结束时增加永久生命100。

更多的属性参考：https://github.com/MemeMayhem/ModExamples/wiki/Attributes-zh_CN 。

**Comment by Nagasoyo** [comment]
其实我想问的开局的基础属性修改，是我表述不清了。。。

**Comment by Nagasoyo** [comment]
就是角色的能量上限，大招伤害各种属性，我看有个角色就是开局114能力回复，514能量上限

**Comment by fx013** [comment]
哦，角色的初始属性可以像初始relic/perk chain一样直接设置在角色数据上，可以参考游戏自带角色数据，比如祥子的：https://github.com/MemeMayhem/ModExamples/blob/main/References/CharacterData/SakikoCharacterData.lua.txt#L17-L20

```lua
    attributes = {
        health_maximum = 2200,
        start_gold = -200,
    },
```

**Comment by Nagasoyo** [comment]
非常感谢
