### ISSUE TITLE
请问如何直接赋予子弹效果

### ISSUE THREAD

**Issue by FasciA647** [MemeMayhem/ModExamples#44]
您好，我看到了通过perk behavior可以在拥有能力时让子弹触发某些效果。但请问怎样能像冰块、吸血鬼一样不通过能力/神器，直接让子弹本身拥有添加buff、修改属性值等效果？或者怎样添加初始能力/神器而不在界面上显示？

**Comment by fx013** [comment]
游戏内置的子弹实现方式不太一样，目前在Mod里没法不用perk/relic实现同样的效果。能力和神器也没有办法隐藏。如果用神器实现并且显示出来，这样会造成什么问题吗？

**Comment by NinjaAqua445** [comment]
冰块，吸血鬼可以用我们的mod API实现类似的效果：
在定义冰块perk的时候添加一个减攻速的behavior：
```lua
behavior = {
    description = DCEI.GetTranslationText(
        "combat/behavior/generic_decrease_duration/description",
        { x = TAG.attack_speed }
    ),
    buff_bar_icon = DCEI.Texture("flat_icon_emoji_ice_1f9ca_ipick"),
    duration = 3,
    non_scaling_attributes = {
        attack_speed = -0.01,
    },
},
```
然后在注册冰块子弹命中的回调函数里施加相应的behavior：
```lua
combat_unit:RegisterOnMissileImpactCallback(name, function(level, attack_data, caster, target)
    PerkBehaviorSystem:ApplyPerkBehavior(target, caster, perk_name)
end)
```
吸血鬼也可以用类似的方法实现，在注册吸血鬼子弹命中的回调函数中扣除敌人的生命值上限，然后向自己发射一个血液子弹，血液子弹命中的回调函数里添加回复自己的生命值即可。
更详细的内容请参考我们的mod examples和[Wiki](https://github.com/MemeMayhem/ModExamples/wiki)。

**Comment by FasciA647** [comment]
感谢解答！

**Comment by FasciA647** [comment]
不过在perk中实现好像不能对初始的子弹生效，我想创建初始就带有很多不同特殊子弹的角色，就采用添加初始神器吧。

**Comment by fx013** [comment]
@FasciA647 Perk也可以让角色初始就有，参见这个FAQ：https://github.com/MemeMayhem/ModExamples/wiki/FAQ-zh_CN#%E6%80%8E%E4%B9%88%E4%BF%AE%E6%94%B9%E8%A7%92%E8%89%B2%E7%9A%84%E5%88%9D%E5%A7%8B%E5%B1%9E%E6%80%A7%E5%92%8C%E5%88%9D%E5%A7%8B%E8%83%BD%E5%8A%9B
