### ISSUE TITLE
可不可以给自机角色添加垃圾话

### ISSUE THREAD

**Issue by qq654621814** [MemeMayhem/ModExamples#45]
如题，应该怎么添加？

**Comment by GoodCrispyShark** [comment]
你是想修改目前的垃圾话内容 还是新建垃圾话相关的能力？

**Comment by qq654621814** [comment]
我已收到您发送的电子邮件，谢谢您对我工作的支持。如果需要第一时间回复请电话联系我。Thank?6?8you?6?8for?6?8contacting?6?8me.?6?8Unfortunately?6?8I?6?8am?6?8away?6?8from?6?8my?6?8email?6?8right?6?8now,?6?8but?6?8I?6?8will?6?8reply?6?8to?6?8you?6?8on?6?8my?6?8return.?6?8

**Comment by qq654621814** [comment]
> 你是想修改目前的垃圾话内容 还是新建垃圾话相关的能力？

我想新建垃圾话，准确的说是给创建的MOD角色不断的说各种垃圾话，但是并不与子弹直接相关，而是开局以后不断的说直到游戏结束
