### ISSUE TITLE
Bugged perk chains

### ISSUE THREAD

**Issue by Jonathan-Hollingsworth** [MemeMayhem/ModExamples#47]
My mod isn't registering my character's perk chains and bugging out

`perk_chains = {
  {
     "attack_key_blast",
     "key_on_key",
  },
  {
    "attack_flex",
    "damage_heal",
    "flex_quest",
    "super_flex",
    "gain_attack",
    "attack_quest",
    "damage_to_health",
    "flex_on_flex",
    "ultimate_power",
    "ultimate_quest",
    "attack_speed",
    "attack_speed_buff",
    "speed_luck",
    "dodge",
    "energy_on_dodge",
    "dodge_on_crit_quest",
    "crit",
    "crit_damage",
    "crit_chance_quest",
  },
}`

I originally had multiple chains set up

`perk_chains = {
  {
    "attack_flex",
    "damage_heal",
    "flex_quest",
    "super_flex",
  },
  {
    "gain_attack",
    "attack_quest",
    "damage_to_health",
    "flex_on_flex",
  },
  {
    "attack_key_blast",
    "key_on_key",
  },
  {
    "ultimate_power",
    "ultimate_quest",
  },
  {
    "attack_speed",
    "attack_speed_buff",
    "speed_luck",
  },
  {
    "dodge",
    "energy_on_dodge",
    "dodge_on_crit_quest",
  },
  {
    "crit",
    "crit_damage",
    "crit_chance_quest",
  },
}`

I have no idea how it's going wrong (the new perks are made before the character, and I spelled the perks correctly)

**Comment by fx013** [comment]
Can you follow the [Troubleshooting guide](https://github.com/MemeMayhem/ModExamples/wiki/Troubleshooting#what-if-the-game-gets-stuck-at-the-loading-screen-or-is-totally-broken) to see what's going on the `Player.log` file? That should give you some ideas about what went wrong.

**Comment by Jonathan-Hollingsworth** [comment]
I was using the wrong id for a perk. I had `"attack_speed_buff"` instead of  `"rush_speed_buff"` OOF!!

The moral of the story is to always double and triple check the id that you want to copy.
