### ISSUE TITLE
可不可以直接为Mod角色提供难度解锁?

### ISSUE THREAD

**Issue by WixauoPump** [MemeMayhem/ModExamples#48]
如题, 如果我想要测试人物在30难下的强度的话总不至于每次都先通关30次吧?
或者说能不能让Mod在更新后依然保持以前的最高难度?
目前的情况似乎是一旦有更新就得从0难打起

**Comment by NinjaAqua445** [comment]
您好，mod API暂时不支持修改存档的功能（例如修改已解锁难度）。我们将持续更新mod API，这个功能将会在后续逐步加入。 @MajorMajorMajor6
