### ISSUE TITLE
TAG pull

### ISSUE THREAD

**Issue by KingofApples** [MemeMayhem/ModExamples#5]
Could we get a command to pull TAGS like how the other ones were recently added?

For example, I'm trying to pull the attribute "energy_per_second" as a TAG to put in a perk's description, but the TAG is not called energy_per_second and causes a crash. I'd love to be able to view the available tags somehow.

**Comment by KingofApples** [comment]
Having the same issue pulling the armor icon. It's listed as "block" and both block and armor don't work and cause crashes.

**Comment by KingofApples** [comment]
For reference I'm using the command "Api.GameMechanicTags.TAG.attack" "Api.GameMechanicTags.TAG.block" etc

**Comment by fengx1024** [comment]
I have added the GameMechanicTags.lua.txt file to the repo for your reference: https://github.com/MemeMayhem/ModExamples/blob/main/References/GameMechanicTags.lua.txt

Besides `GameMechanicTags.TAG`, there are other ones like `EMOJI`, `RELIC_ICON`, etc.

**Comment by fx013** [comment]
See the GameMechanicTags.lua.txt reference file: https://github.com/MemeMayhem/ModExamples/blob/main/References/GameMechanicTags.lua.txt
