### ISSUE TITLE
如何显示自定义能力的层数（如：努力锻炼）

### ISSUE THREAD

**Issue by GSMUZILI** [MemeMayhem/ModExamples#50]

**Comment by GSMUZILI** [comment]
1. 已经解决显示自定义层数。
2. 如何归零？

**Comment by GSMUZILI** [comment]
> 1. 显示自定义层数（已经解决）
> 2. 如何归零？（已经解决）
> 3. 如何层数达到最大时，立即清零？

**Comment by GSMUZILI** [comment]
> > 1. 显示自定义层数（已经解决）
> > 2. 如何归零？（已经解决）
> > 3. 子弹如何一层一层的加？

**Comment by fx013** [comment]
类似努力锻炼的例子可以参考这个：https://github.com/MemeMayhem/ModExamples/tree/main/Medium-PerkQuest

**Comment by GSMUZILI** [comment]
> 类似努力锻炼的例子可以参考这个：https://github.com/MemeMayhem/ModExamples/tree/main/Medium-PerkQuest

能力：复仇的计数器怎么写
