### ISSUE TITLE
如何让  自己向自身发射的子弹  命中自身后   向敌人发射新子弹？

### ISSUE THREAD

**Issue by FasciA647** [MemeMayhem/ModExamples#51]
如题。如果使用combat_unit.Attack:NewMissileAttack(target/caster,name)
无论是发射者还是受击者都是自己，怎样向敌人发射呢？

**Comment by fx013** [comment]
如果是自己向自己发射的子弹，caster/target都是自己，所以你不管用哪个都还是向自己发射子弹。要向对手发子弹需要用`combat_unit:GetMainOpponent()`获取对手，比如：

```lua
local opponent = combat_unit:GetMainOpponent()
combat_unit.Attack:NewMissileAttack(opponent, "attack_rock")
```

上面的代码不管在什么情况下触发都会向对手发一个石头。
