### ISSUE TITLE
如何在文本描述里获取属性值，不是图标

### ISSUE THREAD

**Issue by GSMUZILI** [MemeMayhem/ModExamples#53]

**Comment by GSMUZILI** [comment]
description = "造成".. Api.GameMechanicTags.TAG.attack .. "伤害" --获取图标

**Comment by GSMUZILI** [comment]
2. 自定义属性如何不显示

**Comment by MajorMajorMajor6** [comment]
试一下这个
![image](https://github.com/user-attachments/assets/0c353430-0655-4b23-ab20-81a5d8d9c8af)

**Comment by MajorMajorMajor6** [comment]
至于文本描述里获取属性值，现在还不支持，目前都是写死的数字

**Comment by GSMUZILI** [comment]
> 至于文本描述里获取属性值，现在还不支持，目前都是写死的数字

好的，谢谢
