### ISSUE TITLE
添加的新事件没有效果

### ISSUE THREAD

**Issue by fuxiao1563** [MemeMayhem/ModExamples#54]
添加的新事件和修改事件池没有效果，可以请大佬们看一下是哪出问题了吗
[Rance Mod.zip](https://github.com/user-attachments/files/17097417/Rance.Mod.zip)

**Comment by fx013** [comment]
事件的API好像出问题了， @MajorMajorMajor6 帮忙看下吧

**Comment by MajorMajorMajor6** [comment]
将在下一个版本修复 (0.20.144 or 0.20.144+)
