### ISSUE TITLE
我按照范例为角色添加的新boss池会导致mod角色上锁的bug

### ISSUE THREAD

**Issue by lizncu111** [MemeMayhem/ModExamples#55]

**Comment by MajorMajorMajor6** [comment]
这个大都是因为mod代码会抛exception。请仔细检查你的脚本

**Comment by fx013** [comment]
@lizncu111 参考这个guide: https://github.com/MemeMayhem/ModExamples/wiki/Troubleshooting

**Comment by fuxiao1563** [comment]
你自己的mod的id可能和别人mod的id重复了
