### ISSUE TITLE
似乎并没有看到有子弹的代码

### ISSUE THREAD

**Issue by Nagasoyo** [MemeMayhem/ModExamples#56]
想做类似冰这种降低对方属性的子弹，想找子弹的代码学习一样，然而似乎并没有发现有子弹的代码，reference里只有神器能力角色的代码

**Comment by Nagasoyo** [comment]
我是设想是做个能减少对方回血的子弹，然而只有能力卡有类似的效果，不知道怎么才能让子弹直接拥有这种效果

**Comment by MajorMajorMajor6** [comment]
可以注册一个新的神器，然后这个神器的功能是每次子弹击中发生效果：https://github.com/MemeMayhem/ModExamples/blob/main/Advanced-Mod2/additions/scripts/Trigger.lua.txt#L169

**Comment by Nagasoyo** [comment]
不能像冰这种，攻击之后直接上debuff吗

**Comment by fx013** [comment]
@Nagasoyo Mod里的子弹不能像内置子弹一样自带效果，必须由能力或者神器来辅助实现。这个问题这里也有人问：https://github.com/MemeMayhem/ModExamples/issues/44

**Comment by Nagasoyo** [comment]
哦，这样，麻烦了
