### ISSUE TITLE
Medium-PoisonTimer text sprites not working

### ISSUE THREAD

**Issue by Honey-snake** [MemeMayhem/ModExamples#57]
In the example "Medium-PoisonTimer" the text sprites do not work. Only blue orbs are displayed instead of the indicated sprites. (See image)
![20240923183207_1](https://github.com/user-attachments/assets/b0d8e5dd-4250-40c9-a4ec-3ba075fdce94)

**Comment by fx013** [comment]
@Honey-snake Hi, thanks for catching the issue. The current game version doesn't support custom text sprites yet. It will be supported in the next game release.

**Comment by Honey-snake** [comment]
Ok thank you for the update!

**Comment by fx013** [comment]
@Honey-snake It works now with the latest game version. I have added screenshots as well: https://github.com/MemeMayhem/ModExamples/tree/main/Medium-PoisonTimer
