### ISSUE TITLE
如何在描述中引用属性图标

### ISSUE THREAD

**Issue by Nagasoyo** [MemeMayhem/ModExamples#59]
我在示例中看到这个代码能引用伤害的图标"造成 <color=green>50%</color> " .. Api.GameMechanicTags.TAG.attack .. "伤害"
把attack改成attack_speed可以显示攻速的图标，但改成生命回复的ID，health_per_second时却会导致mod角色上锁，会有bug，如果我想用生命回复的图标，该怎么写呢，如果是其他属性又要怎么写，这似乎并不是改成属性ID就可以的。

**Comment by Nagasoyo** [comment]
description = "降低<color=#2fc107>1</color>".. Api.GameMechanicTags.TAG.health_per_second .. "",

这是我脚本中填写的代码

**Comment by Ill-cat** [comment]
图标我是在这里面找的
https://github.com/MemeMayhem/ModExamples/blob/main/References/GameMechanicTags.lua.txt
有的属性id和他的图标id不一致是有点(

**Comment by Ill-cat** [comment]
比如再生的图标是Api.GameMechanicTags.TAG.health_regen

**Comment by fx013** [comment]
游戏自带的图标可以在reference里找到：https://github.com/MemeMayhem/ModExamples/blob/main/References/GameMechanicTags.lua.txt 。 有些名字并不一一对应，有些还有typo，复制id时要注意一下……

文字描述里加自定义图标的功能在最新版的游戏里有了，示例：https://github.com/MemeMayhem/ModExamples/tree/main/Medium-PoisonTimer

![image2](https://github.com/user-attachments/assets/32b089e7-12b6-4aec-8053-596dde5fb9be)
