### ISSUE TITLE
能力包制作

### ISSUE THREAD

**Issue by yangjiandendi** [MemeMayhem/ModExamples#6]
我想制作一个简单的修改属性的能力包，比如说血上限+500，回血-10.
但是没能找到相关的例子，请问可以提供一个类似的例子吗？

**Comment by fx013** [comment]
我在Basic-NewPerk里加了一个增加基础属性的例子（血上限+500，回血-10）：https://github.com/MemeMayhem/ModExamples/commit/5ae5064cc43c801b3f8b0a51fd393f193f0440c6

![image](https://github.com/user-attachments/assets/97e8177d-3eaf-4353-9b1a-576ba74d75a6)

基础属性的列表参见：https://github.com/MemeMayhem/ModExamples/wiki/Attributes-zh_CN
