### ISSUE TITLE
能整理个可用api的表吗

### ISSUE THREAD

**Issue by wen-bug** [MemeMayhem/ModExamples#60]
wiki的教程纯散装从哪里调用都不知道，每个接口可以属性也不知道例子一个注释不带自带加密是吧😡😡

**Comment by helihydrogen** [comment]
+1，GetPerks我试了好久，要不是直接拿出来问我都不知道输出的table是key-value还是纯array

**Comment by MajorMajorMajor6** [comment]
模组可用的api基本在这里看到：
https://github.com/MemeMayhem/ModExamples/wiki/CombatUnit-Methods-zh_CN
https://github.com/MemeMayhem/ModExamples/wiki/AttackManager-Methods-zh_CN
https://github.com/MemeMayhem/ModExamples/tree/main/References

**Comment by MajorMajorMajor6** [comment]
例子有哪里不清楚可以贴出来，也方便其他人

**Comment by fx013** [comment]
Mod API大部分来自游戏本体，游戏本体也用Lua实现的，并且缺少注释，因此我们目前并没有办法自动生成API文档。完整的文档只能等我们有更多人手的时候才有可能去做。

上面 @MajorMajorMajor6 列出的是我们最近刚整理出来的部分文档和游戏本体代码作为参考。我们会根据大家问的问题优先整理出最需要部分的文档和示例。如果你有更具体的问题，欢迎提问。
