### ISSUE TITLE
能力卡怎样能做到删掉自身一个子弹

### ISSUE THREAD

**Issue by a3662981** [MemeMayhem/ModExamples#62]
删除一个自身已拥有的子弹

**Comment by fx013** [comment]
你可以这样删除子弹：
```lua
combat_unit.Attack:RemoveEmojiFromDeck("attack_rock")
combat_unit.Attack:ResetMagazine()
combat_unit:UpdateEmojiMagazineUi()
```
第一行从当前deck删除，第二行重载弹夹（不重载的话已经删除的子弹可能还会再发射一次直到弹夹用完自动重载），第三行是重置UI。

这个只能在一场战斗中临时删除，并不能永久删除子弹（因为子弹可能是由其他perk/relic添加的，上面的代码并不能让其他的perk/relic失效）。

**Comment by a3662981** [comment]
感谢

**Comment by FasciA647** [comment]
能够删除敌人的子弹吗？怎么样读取弹夹中某个位置上子弹的id，或者不是按照子弹id，而是删除某个位置上的子弹呢？
