### ISSUE TITLE
如何直接获取e币？

### ISSUE THREAD

**Issue by fuxiao1563** [MemeMayhem/ModExamples#64]
在表格里只看到了收入 income ，怎么能直接获取e币（如直接拿到400块的卡）
https://github.com/MemeMayhem/ModExamples.wiki.git

**Comment by Ill-cat** [comment]
Api.AddGold(Api, 5)

**Comment by fuxiao1563** [comment]
> Api.添加黄金（Api，5）

对不起，好像我的描述有问题......
我想实现的是在事件选择中直接获取，不是在能力牌里
```
{
	flavor = "+80e币",
	description = "+80e币",
	aftermath_narrative = " +80e币",
	aftermath_description = "+80e币",
},
```

**Comment by Ill-cat** [comment]
哦莫,我还没试过做事件,不过看了下应该可以试着用给+80金的神器来临时解决一下(

**Comment by fx013** [comment]
事件选项产生的效果可以参考`ChoiceData.lua.txt`，比如增加金币的例子：https://github.com/MemeMayhem/ModExamples/blob/main/References/ChoiceData.lua.txt#L1785-L1787
