### ISSUE TITLE
有获取脑子损毁能量的方法吗

### ISSUE THREAD

**Issue by Ill-cat** [MemeMayhem/ModExamples#65]

**Comment by fx013** [comment]
修改角色能量用`CombatUnit:ModifyCurrentEnergy`。角色API参见：https://github.com/MemeMayhem/ModExamples/wiki/CombatUnit-Methods-zh_CN

**Comment by Ill-cat** [comment]
怎么关了,我问的是根据脑子损毁能量来进行其他值计算的方法,像头脑风暴那样根据损毁的能量来恢复自己能量(

**Comment by fx013** [comment]
内置子弹脑子的实现和头脑风暴等能力卡是绑定死的，在它的实现里会根据有没有`bonus_brain`, `mind_blown`,`super_brain`等等进行不同的处理。自定义能力或者神器没法加入到这个计算里面。

**Comment by NinjaAqua445** [comment]
脑子损耗多少能量是定义在perk data里的。如果你创建了自己的脑子能力卡，那么可以通过API来获取你在perk data里定义的数值，然后根据获取到的数值削减能量。
例如：https://github.com/MemeMayhem/ModExamples/blob/main/References/PerkRelicRegisterCallbackData.lua.txt#L970

**Comment by fx013** [comment]
@NinjaAqua445 说的方法只能拿到定义在子弹数据里的常量值，受到能力加成后在游戏中的实际消减能量只有脑子子弹自己的实现可以拿到。

**Comment by Ill-cat** [comment]
这样,那我先换一下方向了,以后会考虑支持吗

**Comment by fx013** [comment]
目前不打算支持这种特定子弹的特定临时变量的API，一是加起来会没完没了，二是会影响我们修改游戏本体。我的建议是做一套自定义的脑子子弹和相应的能力卡，这样你想要做的各种扩展都更容易实现，然后也能减小受到游戏本体调整的影响。

**Comment by Ill-cat** [comment]
我想了下用HasPerk和GetPerkLevel获取和判断是否有增加了脑子损毁的能量的能力然后再来自己算是不是可行🤔,刚好游戏里增加脑子损毁能量的能力和神器也不是很多
