### ISSUE TITLE
抗压神器没有显示，也没有生效

### ISSUE THREAD

**Issue by iddsxbk** [MemeMayhem/ModExamples#66]
就什么都没改，直接复制一个过来测试也没有在mod界面出现，游戏内也没有生效

**Comment by fx013** [comment]
建议先按教程完成第一个Mod：https://github.com/MemeMayhem/ModExamples/wiki/Tutorial-zh_CN

然后看看怎么处理一些常见问题：https://github.com/MemeMayhem/ModExamples/wiki/FAQ-zh_CN
