### ISSUE TITLE
Relic id dictionary is not complete

### ISSUE THREAD

**Issue by smght1** [MemeMayhem/ModExamples#7]
Hi, currently https://github.com/MemeMayhem/ModExamples/wiki/Relics lacks IDs for some of the relics, such as: Suit, Perk Printer (it is perk_printer though as I have found out), Poo Curry, Rebellion, Sugar meter, Juxtapose, Cracked F5 and some more I think.

Additionally, relic start_robot breaks the game for me.

Could you please add these and any other relics and perks that are not listed there currently?

**Comment by fx013** [comment]
Thanks for bringing this up. I didn't notice that the `Api:PrintRelics()` function actually only prints a partial list. We'll fix the API tomorrow (requires a new game build) and update the list.

**Comment by fx013** [comment]
@MajorMajorMajor6 is looking into this issue.

**Comment by MajorMajorMajor6** [comment]
we have made a fix, the wiki pages are updated already.
print functions output will include character relics and gift relics, this expected to be in the next release: 0.20.130
