### ISSUE TITLE
设置target_self = true的子弹攻击自己是不是也会触发闪避判定(

### ISSUE THREAD

**Issue by Ill-cat** [MemeMayhem/ModExamples#71]
![image](https://github.com/user-attachments/assets/faf07207-b71f-4eb5-b1d8-3e3443bd0498)

![image](https://github.com/user-attachments/assets/0a6bdf15-f7b3-4837-8162-53fc36c9ddbc)
顺便问一下有没有让子弹不可闪避的属性

**Comment by fx013** [comment]
`target_self = true`的子弹不会被闪避。子弹是否闪避可以在能力或者神器的回调里改写：
```lua
combat_unit.Attack:RegisterOnMissileImpactCallback(name, function(level, attack_data, caster, target)
    if attack_data.missile_id == "attack_rock" then
        attack_data.is_dodged = false
    end
end)
```
如果给角色装上有上述实现的能力或者神器，`attack_rock`就不会被闪避。
