### ISSUE TITLE
自定义属性报错

### ISSUE THREAD

**Issue by fuxiao1563** [MemeMayhem/ModExamples#72]
按照案例做的，案例可以生效，但mod就会出错....
附mod文件和日志
[Rance Mod.zip](https://github.com/user-attachments/files/17157459/Rance.Mod.zip)
[Player.log](https://github.com/user-attachments/files/17157457/Player.log)

Api:RegisterAttribute({
        id = "loki_armor_attribute",
        display_name = "洛基的铠甲",
        description = "受到<color=green>10</color>次攻击后, 增加<color=green>2</color>" .. Api.GameMechanicTags.TAG.heal,
        icon = DCEI.Texture("loki_armor"),
        display_type = Api.DisplayType.Integer,
        is_neutral = true, -- if true, font color will always be white
        flavor_text = "This is flavor text for a custom quest attribute",
        display_requirements = {
            is_hero = true, -- only show for hero
            default_value = 0,
            max = 10 -- for visual only, you need to keep current value <= max
        },
    })

**Comment by Ill-cat** [comment]
把Api.GameMechanicTags.TAG.heal改成Api.GameMechanicTags.TAG.health就好了

**Comment by fuxiao1563** [comment]
> 把Api.GameMechanicTags.TAG.heal改成Api.GameMechanicTags.TAG.health就好了

谢谢...我铸币了.
