### ISSUE TITLE
bug，mod事件设置事件的图如果图的参数名和其他mod一样可能会出现变成其他图片

### ISSUE THREAD

**Issue by a3662981** [MemeMayhem/ModExamples#73]
本身mod事件图片测试正常上传之前没问题，上传后别人玩时发现事件图片变成别的图了，因为他装了别的很多mod，猜测可能是设置事件图片名参数相同时会引用其他mod的图片

**Comment by fx013** [comment]
mod和游戏本体以及mod和mod之间并不是完全隔离的。mod里能使用游戏本体的资源，mod之间也能使用其他mod的资源。如果不是故意重名的话（一个mod可以引用另一个mod并做修改），建议在命名时加上一个唯一的前缀避免这种冲突。
