### ISSUE TITLE
更新后bug，刚游戏更新了版本，所有mod全部mod人物形象全部变为原始系统形象了

### ISSUE THREAD

**Issue by a3662981** [MemeMayhem/ModExamples#74]
更新后bug，刚游戏更新了版本，所有mod，全部mod人物形象全部变为原始系统形象了，包括自己制作的mod和下载的别人的mod和更新bug后去创意工坊下载的新的mod人物，形象全变初始系统形象了

**Comment by Ill-cat** [comment]
![image](https://github.com/user-attachments/assets/ff48130b-d3b5-4250-bea1-63b6a16c900e)
顺带一提,前个版本的bug,mod人物自带的能力在外面无法正常显示(

**Comment by fx013** [comment]
更新加了人物皮肤，我们正在看怎么和现在的mod兼容

**Comment by fuxiao1563** [comment]
卡牌右侧属性图标的描述偶尔也会出现不全的情况。
![QQ20240926-194300](https://github.com/user-attachments/assets/0bbdb7e7-ef01-4f60-a164-f67ccff574ae)

**Comment by fx013** [comment]
@Ill-cat @fuxiao1563 这个issue是关于更新后mod形象失效的，你们的问题可以单开另外的issue吗？

**Comment by GoodCrispyShark** [comment]
昨晚的0.20.157应该已经修复了
