### ISSUE TITLE
属性图标的描述显示不全

### ISSUE THREAD

**Issue by fuxiao1563** [MemeMayhem/ModExamples#75]
卡牌右侧属性图标的描述偶尔会出现不全的情况。
![QQ20240926-194300](https://github.com/user-attachments/assets/75be4caf-fda4-4f28-8a62-d0c30bb34b54)

**Comment by fx013** [comment]
提示是从数据里提取的，如果数据里没有写加力量/生命，即使回调里加了，也不会显示的。

这种情况你可以给perk加`behavior`或者`extra_tooltips`来告诉游戏显示更多的提示，参考这个issue里的讨论：https://github.com/MemeMayhem/ModExamples/issues/49#issuecomment-2373034993

**Comment by fuxiao1563** [comment]
好的，谢谢

**Comment by fx013** [comment]
@fuxiao1563 想到一个更简单的方法，你可以直接在`modify_attributes`里把要显示提示的属性都列出来，然后值设成0。
