### ISSUE TITLE
有没有在首次获得能力/神器后触发和每次获得其他能力/神器后触发的回调

### ISSUE THREAD

**Issue by Ill-cat** [MemeMayhem/ModExamples#76]

**Comment by NinjaAqua445** [comment]
您好，目前只有在商店购买能力/神器后触发的回调函数 `CombatUnit:RegisterOnBuyPerkCallback(perk_or_relic_name, callback)` `CombatUnit:RegisterOnBuyRelicCallback(perk_or_relic_name, callback)`

**Comment by FasciA647** [comment]
> 您好，目前只有在商店购买能力/神器后触发的回调函数`CombatUnit:RegisterOnBuyPerkCallback(perk_or_relic_name, callback)` `CombatUnit:RegisterOnBuyRelicCallback(perk_or_relic_name, callback)`

请问能让购买任意能力/神器都触发这个回调吗？

**Comment by Ill-cat** [comment]
@FasciA647 这个试过了,可以的
