### ISSUE TITLE
anyway to create custom UI like the winxp ui

### ISSUE THREAD

**Issue by diehard2214** [MemeMayhem/ModExamples#77]
I wanted to know if there was anyway to create a custom ui like the win xp ui for a mod

**Comment by NinjaAqua445** [comment]
Hi, sorry this is not supported yet.

**Comment by GoodCrispyShark** [comment]
win xp UI is pretty complicated and also deeply binded into many XMLs
it is not like a completely different UI pieces that can be replaced easily

but we can start with sth smaller like supporting things like trash talks?
