### ISSUE TITLE
有刷新子弹面板ui的指令，那有没有刷新人物的

### ISSUE THREAD

**Issue by a3662981** [MemeMayhem/ModExamples#78]
combat_unit:UpdateEmojiMagazineUi()这个可以刷新子弹的ui来马上更新子弹的变化，那有没有什么能刷新人物形象的，现在想实现半血更换人物形象，但是形象更新变化只有在回合结束时才会变，也就是只能实现当前回合结束后更换形象，我猜可能是中途更改了形象的数据后并没有再次读取刷新只有回合结束时会读取一次，有没有什么指令可以进行主动刷新的

**Comment by MajorMajorMajor6** [comment]
和这个issue说的是同一件事 https://github.com/MemeMayhem/ModExamples/issues/14

**Comment by MajorMajorMajor6** [comment]
@GoodCrispyShark 等有时间了考虑加一个？

**Comment by GoodCrispyShark** [comment]
好

**Comment by GoodCrispyShark** [comment]
目前换形象有两种

一个是小祥这种只是改形象，缺点是死亡动画不会变，这个比较简单，我们做个actor event就行了
一个是杰哥这种真变身，需要做2个不同的unit，好处是死亡动画也是跟着变的

不知道你想要哪种？

**Comment by a3662981** [comment]
> 目前换形象有两种
> 
> 一个是小祥这种只是改形象，缺点是死亡动画不会变，这个比较简单，我们做个actor event就行了 一个是杰哥这种真变身，需要做2个不同的unit，好处是死亡动画也是跟着变的
> 
> 不知道你想要哪种？

第二种吧，就是在战斗过程中的变身，现在是已经可以做到当前回合结束更换形象了，但是没办法做到回合进行中时的切换形象，就是比如设置回调判断当回合数=xx回合时将角色的icon参数人物的注册参数指向另一个图的注册参数。但是这样的问题就是不管是设置回合数回调还是战斗开始时回调还是受击回调并设置人物图片属性，都只有回合结束时才会发生变化，没法在回合开始或者中途发生变化，所以我猜是不是和删除子弹需要刷新子弹面板的命令一样需要一个刷新人物的命令让人物参数更换之后立刻进行刷新而不是等战斗结束时才进行刷新

**Comment by GoodCrispyShark** [comment]
下次更新时会支持

**Comment by GoodCrispyShark** [comment]
https://github.com/MemeMayhem/ModExamples/wiki/Tutorial-zh_CN#%E5%9C%A8%E6%88%98%E6%96%97%E4%B8%AD%E6%9B%B4%E6%8D%A2%E8%A7%92%E8%89%B2%E5%BD%A2%E8%B1%A1

我添加了战斗中刷新立绘的教程
