### ISSUE TITLE
按照教程做的时候，进战斗发现角色变成石头了

### ISSUE THREAD

**Issue by Haodayizhie** [MemeMayhem/ModExamples#80]
![image](https://github.com/user-attachments/assets/fb17e062-d0d9-4842-b7c9-e3cbd837f808)
在创意工坊下载教程样板mod后打开也变成了石头，发生什么事了

**Comment by Ill-cat** [comment]
可能是角色贴图用错ID了(

**Comment by fx013** [comment]
@Haodayizhie 你看下游戏和示例是否是最新版本（可以试着卸载重装一下）？我用最新的客户端测了一下没发现这个问题。

**Comment by fx013** [comment]
游戏本体和mod asset都是共享的，如果你加了一个石头图片命名成my_character_small.png，那么其他mod里用到my_character_small的地方也会变成石头。看下是不是这个原因。

**Comment by Haodayizhie** [comment]
> 游戏本体和mod asset都是共享的，如果你加了一个石头图片命名成my_character_small.png，那么其他mod里用到my_character_small的地方也会变成石头。看下是不是这个原因。

看了下，发现是我自己弄的图片名没加_large,但文本里有
