### ISSUE TITLE
Custom perks and relics not showing in shop pool

### ISSUE THREAD

**Issue by heartskingu** [MemeMayhem/ModExamples#83]
I've look through the wiki/docs and also asked on discord, but I can't find anywhere explaining how to add new perks/relics to the shop pool. The closest I could find was how to prevent perks/relics from showing up with "blocked_perks" and "blocked_relics". Some modded relics are just too fun to wait for random boss encounters

**Comment by MajorMajorMajor6** [comment]
@GoodCrispyShark is there a shop pool?

**Comment by heartskingu** [comment]
btw, some clarification may be needed. I've registered 5 new perks and relics. Perks do show after combat, but neither show in the shop (I tested with 99 shop rerolls)

**Comment by MajorMajorMajor6** [comment]
we will make custom relics show in the shop soon.
but for perks, could you try use a small perk chain pool and try reroll in the shop? you should be able to see custom perks in the shop

**Comment by heartskingu** [comment]
yeap, I guess I was too focused on relics during my first try. Perks are showing up without a problem with a 4 perk pool. Thank you, I'll wait patiently for the relic shop update :)
