### ISSUE TITLE
怎样将属性设置为指定值

### ISSUE THREAD

**Issue by FasciA647** [MemeMayhem/ModExamples#85]
我想在每次战斗开始时将一个自定义属性设置为100
    function(combat_unit)
        local name = "mod_component"
        combat_unit:RegisterOnCombatStartCallback(name, function (level, target)
            combat_unit:ModifyAttribute("percentage_of_life", 100, false)--用这个可以增加
        end)
            --combat_unit:SetAttribute("percentage_of_life", 100) 这个不知道怎么用
        --end)
    end)

**Comment by fx013** [comment]
你可以这样写：
```lua
local current_value = combat_unit:GetBoundedAttribute("percentage_of_life")
combat_unit:ModifyAttribute("percentage_of_life", 100 - current_value, false)
```

**Comment by FasciA647** [comment]
好的，谢谢
