### ISSUE TITLE
是否有每隔一段时间触发的回调？

### ISSUE THREAD

**Issue by FasciA647** [MemeMayhem/ModExamples#86]
如题，比如每秒触发1次。

**Comment by fx013** [comment]
时间回调用timer，一秒之后执行操作的例子：

```lua
Api:RunCombatOnlyTimer(function()
    PoisonTick(target)
end, 1)
```

可以参考这个：https://github.com/MemeMayhem/ModExamples/blob/main/Medium-PoisonTimer/additions/scripts/Trigger.lua.txt#L32

**Comment by FasciA647** [comment]
谢谢

**Comment by FasciA647** [comment]
另外被子弹/大招击中时触发应该怎么使用呢？

**Comment by fx013** [comment]
被子弹和大招击中的回调是这两个：
```lua
AttackManager:RegisterOnMissileHitCallback(perk_or_relic_name, callback)
AttackManager:RegisterOnUltimateHitCallback(perk_or_relic_name, callback)
```
Wiki上可以查到：https://github.com/MemeMayhem/ModExamples/wiki/AttackManager-Methods-zh_CN

示例里有用`RegisterOnMissileHitCallback`的，可以看看

**Comment by FasciA647** [comment]
谢谢。虽然看了wiki，只从名字不确定是什么作用，要是能加点注释就好了。
