### ISSUE TITLE
部分Perk无法放入卡池中？

### ISSUE THREAD

**Issue by fuxiao1563** [MemeMayhem/ModExamples#87]
冰，冰盾反制，深度冻结，蚌住，冰晶化。
这几张卡一放进去就会报错，是要求特定角色才能用吗

**Comment by Ill-cat** [comment]
应该没有这种要求,这几张卡我也放过

**Comment by fuxiao1563** [comment]
> 应该没有这种要求,这几张卡我也放过

主要是出问题的牌太多了...id也没有重复。我再私下排查一下吧）

**Comment by Ill-cat** [comment]
比较快排查bug的方法:
打开C:\Users\用户\AppData\LocalLow\Cr3 Studio\Meme Mayhem\Player.log
在里面Crtl+F搜你的mod角色名字
如果搜到了会有类似
```
LuaExceptionWithStackTrace: [string "UGC-Mods-茸泽/Trigger.lua.txt"]:2276:
```
的报错
比如上面这个就是跳到你mod Trigger.lua.txt文件的2276行有错误
这个方法可以轻松查找除了ID混乱以外的大部分bug
