### ISSUE TITLE
Additional references

### ISSUE THREAD

**Issue by AirHater** [MemeMayhem/ModExamples#88]
hey, i was looking through current documentation while trying to create couple of mods, but i couldnt find some of the answers that i was looking for. so:

1. is it possible to see some extensive reference list of existing characters. I am mainly looking for Eggs/Evolution (not just quests/counters, but also emojis transformation) and Wish (relic creation from perks, maybe even from perks + relics?).

2.  is it possible to fiddle with the shop? for example change base shop prices/make it so shop prices are doubled on any purchase/change behaviour on rerolls.

3. how should i standardize content for modded stuff, ie if i want to have a list of perks/attributes like in https://github.com/MemeMayhem/ModExamples/blob/aaaa8e1cebfdd675b3521cd400b44b7415c1148f/References/PerkRelicRegisterCallbackData.lua.txt#L293

4. is it possible to create a mod which would be just relic/event/boss pack? and than let people encounter them on any other people mods, or its only possible on a single mod release for now?

**Comment by GoodCrispyShark** [comment]
1. Egg is a bit tricky and there are several parts being hard coded. I will try to make a better doc probably sometime next week
2. Not supported yet. But you can probably make a relic that give negative discount after reroll
3. Are you asking how to make scaling and non-scaling values in perk?
4. I dont think this is supported yet, but this is an interesting idea. @MajorMajorMajor6 @fx013 what do you guys think about this?

**Comment by AirHater** [comment]
1. so is there a way to implement Wish relic behavior, or the better documentation was referring ot this aswell?

2. i found in https://github.com/MemeMayhem/ModExamples/blob/aaaa8e1cebfdd675b3521cd400b44b7415c1148f/Basic-ModDifficulty/additions/scripts/Trigger.lua.txt that you can adjust the scaling of the prices, but no starting price i presume (i also found "price_weight" for perks in https://github.com/MemeMayhem/ModExamples/blob/aaaa8e1cebfdd675b3521cd400b44b7415c1148f/References/PerkData.lua.txt, but nothing similar in relics? what does that value even do, since its 0 for commons).

3. if i want to create a list of perks, to reference later for non-/scaling values. it seems like it it calls for external "libraries" with something like https://github.com/MemeMayhem/ModExamples/blob/aaaa8e1cebfdd675b3521cd400b44b7415c1148f/References/PerkRelicRegisterCallbackData.lua.txt#L12 but how is it handled? i have some experience in coding, but Lua is dark magic to me.

(not sure if adding new questions in this thread is correct, so let me know if it isnt)

5. what does luck do in regards to rarity? it doesnt seem to affect relic drop rates, but for perks - is it weight X (luck + 1) for all rares and above?

6. is there a way to add/adjust boss pool, without having all 6 bosses be constant? ie https://github.com/MemeMayhem/ModExamples/blob/aaaa8e1cebfdd675b3521cd400b44b7415c1148f/Basic-NewBoss/additions/scripts/Trigger.lua.txt#L58

7. is there a way to overwrite values of the existing/base game content, without banning that and readding it with new values? ie if i want to change certain perk behaviour for specific modded character, or outcomes from some choices from specific events?

**Comment by GoodCrispyShark** [comment]
1. Wish and Trash Gather do not have a callback for now. If you want it, make a new issue requesting an `on_apply perk callback`

2. Shop growth there is to for adjusting mob difficulty. This is not related to shop price. I think you should look at relic `credit_card` and there is an attribute called `discount`

3. When you register a perk, for example
```Api:RegisterPerk("custom_perk_3_rock", {
        id = "custom_perk_3_rock",
        display_name = "get 3 rocks",
        description = "Give 3 rocks",
        icon = DCEI.Texture("custom_icon_3_rocks"),
        perk_type = "missile",
        rarity = "common",
non_scaling_values={a=2},
scaling_values={b=100},
        attacks = {
            attack_rock = 3,
        },
    })  
```

those values don't do anything but can be referenced later in scripts. usually scaling means it scales with perk level

4. Luck adds to the weight of all the non-common perks. 
5. For now there has to be 6 bosses. We will support more forms later.
6. I am not quite sure actually. You probably could give it a try by register a perk with same id?

**Comment by AirHater** [comment]
thank you for your help. just one more confirmation about one of the questions. i might have expressed myself incorrectly about (3), i wanted to ask how do i use the existing content for callback in the modded content. ie i want to have perk that would trigger Maniac on missile attacks, i thought i could use api like this

`    Api:RegisterPerk(perk.id, perk, function(combat_unit)
        combat_unit.Attack:RegisterOnMissileImpactCallback(perk.id, function(level, attack_data, caster, target)
            if attack_data.is_dodged or (math.random() > 0.2) then
                return
            end
            Api:EnterWraith(combat_unit, level)
        end)
    end)
`
but it didnt work as i hope. similarly `
                Api.PerkChainData.all_perk_chains.gain_attack_chain` to add chains grouped, instead of adding the perks one by one

**Comment by AirHater** [comment]
^ attaching picture for readability, since formatting got lost for some reason
![image](https://github.com/user-attachments/assets/1dc9e0f4-1167-4375-825a-b715da262e66)

**Comment by GoodCrispyShark** [comment]
so you wanna use wraith? 
extra damage and damage reduction hasn't been available to modders yet. feel free to request them as attributes using a seperating issue
