### ISSUE TITLE
如何修改角色从任何途径获取某项属性的倍率

### ISSUE THREAD

**Issue by wula1245** [MemeMayhem/ModExamples#9]
好多角色获取属性的倍率是1，能不能修改角色获取某项属性倍率为更多倍甚至为0

**Comment by fx013** [comment]
@NinjaAqua445 你能帮忙回答这个问题吗？有没有一个属性变化的event callback？

**Comment by NinjaAqua445** [comment]
您好，目前角色并没有属性获取倍率的概念，所有角色都是根据能力卡填写的数值获得相应的属性。例如如果想实现某一个mod角色一张力量卡获得两倍（5*2=10力量）属性建议给这个角色去掉本体里那张5力量的能力卡直接添加一张获得10力量的能力卡。

**Comment by MajorMajorMajor6** [comment]
可以试一下 `function CombatUnit:RegisterOnSetAttributeCallback(perk_or_relic_name, callback)`
callback 参数 attribute, old_value, new_value

调用方式参考：
https://github.com/MemeMayhem/ModExamples/blob/main/Advanced-Mod2/additions/scripts/Trigger.lua.txt#L228C21-L228C46
