### ISSUE TITLE
mod角色的初始能力不正常显示

### ISSUE THREAD

**Issue by Ill-cat** [MemeMayhem/ModExamples#91]
![{4E9A12AC-0007-41B6-9D88-1B174D26BF1F}](https://github.com/user-attachments/assets/f0e8cf0e-fac9-4375-8769-5a4c7a20e674)

**Comment by MajorMajorMajor6** [comment]
应该显示什么？怎么设置的？

**Comment by Ill-cat** [comment]
就比如说我角色初始携带了一个能力嘛
```
Character.perks = {
"gain_attack",
        }
```
正常的话应该把这个能力在左上角的能力栏显示出来(这个在某个版本更新前是正常显示的

**Comment by Ill-cat** [comment]
![{920B53B7-3772-46D0-99B8-2A21531843A1}](https://github.com/user-attachments/assets/76d093b1-a242-4d6f-947c-1eafb55ac269)
卡了个bug,如果正常显示的话应该是这样(仅能力

**Comment by GoodCrispyShark** [comment]
@NinjaAqua445 我记得这个是你写的？
角色初始能力后来废弃没用 没想到还能用吗

**Comment by GoodCrispyShark** [comment]
我看了下 初始能力就没写完过 目前还不支持显示
