### ISSUE TITLE
CombatUnit:ModifyCurrentHealth和CombatUnit:ModifyCurrentEnergy以后会有数字显示吗

### ISSUE THREAD

**Issue by Ill-cat** [MemeMayhem/ModExamples#92]
或者是其他显示数字的方法
像CombatUnit:Heal和CombatUnit:Damage是有数字显示的
(同时希望这东西是可选的

**Comment by MajorMajorMajor6** [comment]
目前energy变化要想有数字显示，可以做个missile

**Comment by MajorMajorMajor6** [comment]
@GoodCrispyShark ：
1. Modify挺不明确的，Set或者Inc （increase）更明确一点。
2. API名字没有明确说明有没有浮动数字显示

**Comment by GoodCrispyShark** [comment]
heal和damage本来也是没数字的啊 
但是因为结算治疗增强和易伤在终端，如果数字写外面等于要算两遍才移进去的

我们有set方法，modify是加减，set是直接设置。不过set比较危险而且缺少ui api配合暂时没有开放吧

显示数字可以暂时用
```
args = args or {}
    args.color = args.color or Color:Tag("yellow")
    args.size = args.size or "<size=100%>"
    args.center_at_unit = true

    Util.DisplayFloatingCombatText(unit_data, amount, args)
```

**Comment by Ill-cat** [comment]
这样也行,不过直接用你这个给我报了个
```
attempt to index a nil value (global 'Util')
```

**Comment by GoodCrispyShark** [comment]
那看来目前还不支持，我有空支持一下
