### ISSUE TITLE
可否监听或修改对手的大招相关信息

### ISSUE THREAD

**Issue by DeuteriumLight** [MemeMayhem/ModExamples#95]
目前监听大招的发射与命中等方法似乎只能挂在自己身上，是否存在方法监听对手的大招发射或命中呢？
另外是否有方法可以暂时修改对手的大招效果，比如对手的大招原本造成500伤害，某relic触发后改为对我造成300伤害，对他自己造成200伤害呢？

**Comment by NinjaAqua445** [comment]
您好，我们有 `AttackManager:RegisterOnUltimateHitCallback(perk_or_relic_name, callback)` API，这个回调函数将在`combat_unit`被大招击中的时候被调用。
```lua
combat_unit.Attack:RegisterOnUltimateHitCallback("YOUR_RELIC_NAME", function (level, attack_data, caster, target)
    -- caster是发射大招的combat_unit，target是被大招击中的combat_unit
    -- 修改attack_data可以调整大招伤害，用法和missile命中相关的回调函数相同
end)
```
[Wiki](https://github.com/MemeMayhem/ModExamples/wiki/AttackManager-Methods-zh_CN)
