### ISSUE TITLE
请问RegisterOnUltimateHitCallback的触发是否受闪避影响

### ISSUE THREAD

**Issue by DeuteriumLight** [MemeMayhem/ModExamples#97]
你好，之前我提问想要监听敌方的大招发射，得到的建议是使用RegisterOnUltimateHitCallback监听我方被敌方大招击中。
不过关于这个监听我有点疑问，如果我方有闪避敌方大招的能力，请问这回调是闪避结算前就会触发呢，还是在闪避结算后？
如果在我方闪避结算后才触发，那我在这个回调里加入attack_data.is_dodged = false是不是没有效果？
另外，我在这个回调里使用caster:Damage(attack_data.damage, caster, {})来测试敌方大招反伤的效果，但并不起效。
请问这是什么原因呢？

**Comment by DeuteriumLight** [comment]
更新，不能反伤的原因我自己找到了，是我在别的perk把大招伤害变成了0，
犯了低级错误，caster:Damage(attack_data.damage, caster, {})是正常工作的。。。
不过测试后发现一个新问题，如果我方全程没攻击，全靠大招反伤来击杀敌人的话，
战后结算中我方伤害会无显示，没有通常反伤的百分比。请问这个显示有办法处理吗？

**Comment by fuxiao1563** [comment]
反伤是显示的，在进攻属性里面。如果没显示可能是其他问题（？）

**Comment by GoodCrispyShark** [comment]
目前大招闪避不触发闪避回调 如果需要请开一个issue标注需求

我没太看懂第二个问题，是你写了个反伤对方大招的能力，调用damage来伤害对面吗？
