### ISSUE TITLE
开局自选没看到自己创的能力，三选一能选到吗？

### ISSUE THREAD

**Issue by dfgf123** [MemeMayhem/ModExamples#99]

**Comment by fuxiao1563** [comment]
你要在自定义角色中加入这个对象`perk_chains = {}`，然后把perk的id填进去才能看到

**Comment by dfgf123** [comment]
> 你要在自定义角色中加入这个对象`perk_chains = {}`，然后把perk的id填进去才能看到
···
MOD_MANAGER:AddMod(function(Api)

    Api:CopyCharacter("", {
        id = "taffy",
        display_name = "仙人·塔菲",
        short_description = "塔菲不唐喵，不唐，塔菲不唐喵~",
	icon = DCEI.Texture("taffy"),
        icon_low_resolution = DCEI.Texture("taffy_s"), 
        icon_high_resolution = DCEI.Texture("taffy_l"), 
		unit = DCEI.Unit("COMBAT Unit First Mod Character"),
		attack_ids = {
			"bangbang",
			"bangbang",
			"bangbang",
        },
		
		attributes = {
			health_per_second= 22,
			health_maximum= 2222,
		},
		
		perks = {
		},
		
		perk_chains = {
			"bangbang",
		},
		
        relics = {
            "qi",
        },
    })
 ···
 
![a](https://github.com/user-attachments/assets/d261a6ef-376d-4a96-ac87-d73de0864243)

哪里有问题吗？

**Comment by fuxiao1563** [comment]
@dfgf123 `perk_chains = {}`里面至少要有4个才行
